# –ê–Ω–∞–ª–∏–∑ –≤–∑–∞–∏–º–æ—Å–≤—è–∑–∏ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –∏ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏

–≠—Ç–æ—Ç –ø—Ä–æ–µ–∫—Ç –≤—ã–ø–æ–ª–Ω–µ–Ω –≤ —É—á–µ–±–Ω—ã—Ö —Ü–µ–ª—è—Ö –¥–ª—è –¥–µ–º–æ–Ω—Å—Ç—Ä–∞—Ü–∏–∏ –Ω–∞–≤—ã–∫–æ–≤ –∞–Ω–∞–ª–∏–∑–∞ –¥–∞–Ω–Ω—ã—Ö —Å –ø–æ–º–æ—â—å—é **Python** –∏ –±–∏–±–ª–∏–æ—Ç–µ–∫–∏ **pandas**.

## üéØ –¶–µ–ª—å –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è
–ò–∑—É—á–∏—Ç—å, –∫–∞–∫ —É—Ä–æ–≤–µ–Ω—å –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –≤ —Å—Ç—Ä–∞–Ω–∞—Ö –º–∏—Ä–∞ —Å–≤—è–∑–∞–Ω —Å–æ —Å—Ä–µ–¥–Ω–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏.

## üìä –ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ
- **drinks.csv** ‚Äî –¥–∞–Ω–Ω—ã–µ –æ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è (Beer, Spirit, Wine, Total)
- **lifeexpectancy-verbose.csv** ‚Äî –¥–∞–Ω–Ω—ã–µ –æ —Å—Ä–µ–¥–Ω–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ (–ø–æ —Å—Ç—Ä–∞–Ω–∞–º, –ø–æ–ª—É, –≥–æ–¥–∞–º)

---

# –ü—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏–µ –Ω–∞ Python, –ë–ò

## –ù–ò–£ –í–®–≠, 2025-26 —É—á–µ–±–Ω—ã–π –≥–æ–¥

### –û–±—â–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è

__–î–∞—Ç–∞ –≤—ã–¥–∞—á–∏:__ 12.10.2025

__–î–µ–¥–ª–∞–π–Ω:__ 04:00 21.10.2025

### –§–æ—Ä–º–∞—Ç —Å–¥–∞—á–∏

### –û –∑–∞–¥–∞–Ω–∏–∏

–í –¥–∞–Ω–Ω–æ–º –¥–æ–º–∞—à–Ω–µ–º –∑–∞–¥–∞–Ω–∏–∏ –≤—ã –ø–æ–ø—Ä–∞–∫—Ç–∏–∫—É–µ—Ç–µ—Å—å –≤ —Ä–∞–±–æ—Ç–µ —Å –±–∏–±–ª–∏–æ—Ç–µ–∫–æ–π Pandas!

In [113]:
import pandas as pd

In [114]:
#from google.colab import drive
#drive.mount('/content/drive')

In [115]:
drinks = pd.read_csv('drinks.csv')
life_exp = pd.read_csv('lifeexpectancy-verbose.csv')

docs!!!!

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html

### 1

–í —ç—Ç–æ–º –¥–æ–º–∞—à–Ω–µ–º –∑–∞–¥–∞–Ω–∏–∏ –≤—ã –ø–æ—Ä–∞–±–æ—Ç–∞–µ—Ç–µ —Å –¥–∞–Ω–Ω—ã–º–∏ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏ —Å—Ä–µ–¥–Ω–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –ø–æ —Å—Ç—Ä–∞–Ω–∞–º –æ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ —É–ø–æ—Ç—Ä–µ–±–ª—è–µ–º–æ–≥–æ –≤ —Å—Ç—Ä–∞–Ω–µ –∞–ª–∫–æ–≥–æ–ª—è.

–í–∞—à–µ–º—É –≤–Ω–∏–º–∞–Ω–∏—é –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–æ –¥–≤–∞ –¥–∞—Ç–∞—Å–µ—Ç–∞: `drinks.csv` –∏ `lifeexpectancy-verbose.csv`

–ü–µ—Ä–≤–∞—è —Ç–∞–±–ª–∏—Ü–∞ —Å–æ–¥–µ—Ä–∂–∏—Ç –≤ —Å–µ–±–µ —Å–≤–æ–¥–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –ø–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤—É —É–ø–æ—Ç—Ä–µ–±–ª—è–µ–º–æ–≥–æ –∞–ª–∫–æ–≥–æ–ª—è –≤ –∫–∞–∂–¥–æ–π —Å—Ç—Ä–∞–Ω–µ.

–û–ø–∏—Å–∞–Ω–∏–µ –¥–∞—Ç–∞—Å–µ—Ç–∞:
- `country` ‚Äî	Name of the country (String)
- `beer_servings`	‚Äî Number of beer servings per person in the country (Integer)
- `spirit_servings`	‚Äî Number of spirit servings per person in the country (Integer)
- `wine_servings`	‚Äî Number of wine servings per person in the country(Integer)
- `total_litres_of_pure_alcohol` ‚Äî	Total litres of pure alcohol consumed per person in the country (Float)

–í—Ç–æ—Ä–∞—è —Ç–∞–±–ª–∏—Ü–∞ —Å–æ–¥–µ—Ä–∂–∏—Ç –≤ —Å–µ–±–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –Ω–∞—É—á–Ω—ã—Ö —Å—Ç–∞—Ç—å—è—Ö –∏ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è—Ö –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ (–≤ —Ä–∞–∑–Ω—ã—Ö –∫–∞—Ç–µ–≥–æ—Ä–∏—è—Ö –∏ –¥–ª—è —Ä–∞–∑–Ω—ã—Ö –≥—Ä—É–ø–ø) –ø–æ —Ç–æ–π –∏–ª–∏ –∏–Ω–æ–π —Å—Ç—Ä–∞–Ω–µ.

–û—Ç–∫—Ä–æ–π—Ç–µ –≤ –Ω–æ—É—Ç–±—É–∫–µ –æ–±–∞ —Ñ–∞–π–ª–∞ —Å –¥–∞–Ω–Ω—ã–º–∏. –ö–∞–∫–æ–π —Ä–∞–∑–º–µ—Ä –∏–º–µ—é—Ç —Ç–∞–±–ª–∏—Ü—ã? –í—ã–≤–µ–¥–∏—Ç–µ –ø–µ—Ä–≤—ã–µ 5 –∏ –ø–æ—Å–ª–µ–¥–Ω–∏–µ 5 —Å—Ç—Ä–æ–∫ –¥–ª—è –æ–±–µ–∏—Ö —Ç–∞–±–ª–∏—Ü. –°–∫–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Å—Ç—Ä–∞–Ω –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–æ –≤ –∫–∞–∂–¥–æ–π –∏–∑ —Ç–∞–±–ª–∏—Ü? –°–¥–µ–ª–∞–π—Ç–µ –≤—ã–≤–æ–¥—ã.

In [116]:
# —Ä–∞–∑–º–µ—Ä —Ç–∞–±–ª–∏—Ü—ã drinks.csv
drinks.shape

(193, 6)

In [117]:
# —Ä–∞–∑–º–µ—Ä —Ç–∞–±–ª–∏—Ü—ã lifeexpectancy-verbose.csv
life_exp.shape

(6408, 17)

In [118]:
# –ø–µ—Ä–≤—ã–µ –ø—è—Ç—å —Å—Ç—Ä–æ–∫ –æ –Ω–∞—É—á–Ω—ã—Ö –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è—Ö
life_exp.head(5)

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,0,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.0
1,1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.3
2,2,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.0
3,3,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.0
4,4,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.0

In [119]:
# –ø–æ—Å–ª–µ–¥–Ω–∏–µ –ø—è—Ç—å —Å—Ç—Ä–æ–∫ –æ –Ω–∞—É—á–Ω—ã—Ö –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è—Ö
life_exp.tail(5)

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
6403,6403,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,6404,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,6405,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,6406,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,6407,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2013,2013,EUR,Europe,NaN,NaN,ARM,Armenia,BTSX,Both sexes,71,71.02699

In [120]:
# –ø–µ—Ä–≤—ã–µ –ø—è—Ç—å —Å—Ç—Ä–æ–∫ –æ–± —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è
drinks.head(5)

,index,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,0,Afghanistan,0,0,0,0.0
1,1,Albania,89,132,54,4.9
2,2,Algeria,25,0,14,0.7
3,3,Andorra,245,138,312,12.4
4,4,Angola,217,57,45,5.9

In [121]:
# –ø–æ—Å–ª–µ–¥–Ω–∏–µ –ø—è—Ç—å —Å—Ç—Ä–æ–∫ –æ–± —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è
drinks.tail(5)

,index,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
188,188,Venezuela,333,100,3,7.7
189,189,Vietnam,111,2,1,2.0
190,190,Yemen,6,0,0,0.1
191,191,Zambia,32,19,4,2.5
192,192,Zimbabwe,64,18,4,4.7

In [122]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Å—Ç—Ä–∞–Ω –≤ drinks.csv
drinks['country'].nunique()

193

In [123]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Å—Ç—Ä–∞–Ω –≤ lifeexpectancy-verbose.csv
life_exp['CountryDisplay'].nunique()

194

–°—Ç—Ä–∞–Ω–Ω–æ, –æ–¥–Ω–∞ —Å—Ç—Ä–∞–Ω–∞ –≤—ã–ø—É—Å–∫–∞–µ—Ç –Ω–∞—É—á–Ω—ã–µ –º–∞—Ç–µ—Ä–∏–∞–ª—ã –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏, –Ω–æ –ø–æ –Ω–µ–π –Ω–µ—Ç –¥–∞–Ω–Ω—ã—Ö —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è. –ù–∞ –ø–µ—Ä–≤—ã–π –≤–∑–≥–ª—è–¥ –±—Ä–æ—Å–∞–µ—Ç—Å—è —á–∏—Å–ª–æ - 193, —ç—Ç–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –≥–æ—Å—É–¥–∞—Ä—Å—Ç–≤-—á–ª–µ–Ω–æ–≤ –û–û–ù.

In [124]:
# —Ç–µ–ø–µ—Ä—å –Ω–∞–π–¥–µ–º —Å—Ç—Ä–∞–Ω—ã –∫–æ—Ç–æ—Ä—ã—Ö –Ω–µ—Ç –≤–æ 2 —Ç–∞–±–ª–∏—Ü–µ –Ω–æ –µ—Å—Ç—å –≤ 1:
life_exp_set = set(life_exp['CountryDisplay'])
drinks_set = set(drinks['country'])
life_exp_set - drinks_set

{'Antigua and Barbuda',
 'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Brunei Darussalam',
 "C√¥te d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Guinea_Bissau',
 'Iran (Islamic Republic of)',
 "Lao People's Democratic Republic",
 'Micronesia (Federated States of)',
 'Republic of Korea',
 'Republic of Moldova',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Sao Tome and Principe',
 'South Sudan',
 'Syrian Arab Republic',
 'The former Yugoslav republic of Macedonia',
 'Timor_Leste',
 'Trinidad and Tobago',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Republic of Tanzania',
 'United States of America',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam'}

In [125]:
# –∞ —Ç–µ–ø–µ—Ä—å –Ω–∞–π–¥–µ–º —Å—Ç—Ä–∞–Ω—ã –∫–æ—Ç–æ—Ä—ã—Ö –Ω–µ—Ç –≤–æ 1 —Ç–∞–±–ª–∏—Ü–µ –Ω–æ –µ—Å—Ç—å –≤ 2:
drinks_set - life_exp_set

{'Antigua & Barbuda',
 'Bolivia',
 'Bosnia-Herzegovina',
 'Brunei',
 "Cote d'Ivoire",
 'DR Congo',
 'Guinea-Bissau',
 'Iran',
 'Laos',
 'Macedonia',
 'Micronesia',
 'Moldova',
 'North Korea',
 'Sao Tome & Principe',
 'South Korea',
 'St. Kitts & Nevis',
 'St. Lucia',
 'St. Vincent & the Grenadines',
 'Syria',
 'Tanzania',
 'Timor-Leste',
 'Trinidad & Tobago',
 'USA',
 'United Kingdom',
 'Venezuela',
 'Vietnam'}

–ù–µ—Å–ª–æ–∂–Ω–æ –∑–∞–º–µ—Ç–∏—Ç—å, —á—Ç–æ –Ω–∞–∏–º–µ–Ω–æ–≤–∞–Ω–∏–µ —Å—Ç—Ä–∞–Ω –≤ —ç—Ç–∏—Ö –¥–≤—É—Ö —Ç–∞–±–ª–∏—Ü–∞—Ö –≤–æ–∑–º–æ–∂–Ω–æ —Ä–∞–∑–Ω–æ–µ *(–ù–∞–ø—Ä–∏–º–µ—Ä "USA - Unated States of America" –∏ —Ç. –¥.)* –ù–µ—Å–ª–æ–∂–Ω—ã–º–∏ —Ä—É—á–Ω—ã–º–∏ —Å—Ä–∞–≤–Ω–µ–Ω–∏—è–º–∏ –ø–æ–Ω–∏–º–∞–µ–º, —á—Ç–æ —Ç–∞ —Å–∞–º–∞—è —Å—Ç—Ä–∞–Ω–∞ - —ç—Ç–æ –Æ–∂–Ω—ã–π –°—É–¥–∞–Ω ('South Sudan')

–¢–æ –µ—Å—Ç—å –≤ –∏–º–µ–Ω–Ω–æ —ç—Ç–æ–π —Å—Ç—Ä–∞–Ω–µ –Ω–µ—Ç –¥–∞–Ω–Ω—ã—Ö –æ–± —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—å–Ω—ã—Ö –Ω–∞–ø–∏—Ç–∫–æ–≤, –Ω–æ –µ—Å—Ç—å –¥–∞–Ω–Ω—ã–µ –æ –Ω–∞—Å–µ–ª–µ–Ω–∏–∏, –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∏ —Ç. –¥. –í–æ–∑–º–æ–∂–Ω–æ, –ø–æ—Ç–æ–º—É —á—Ç–æ —Å—Ç—Ä–∞–Ω–∞ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –º–æ–ª–æ–¥–∞—è, –æ–Ω–∞ –æ–±—Ä–∞–∑–æ–≤–∞–ª–∞—Å—å –≤ 2011 –≥–æ–¥—É –∏ –¥–∞–Ω–Ω—ã—Ö –≤—Å–µ–≥–æ –Ω–∞–≤—Å–µ–≥–æ –Ω–µ —Å–æ–±–∏—Ä–∞–ª–∏—Å—å –º–µ—Å—Ç–Ω—ã–º–∏ –æ—Ä–≥–∞–Ω–∞–º–∏ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∏; —Ç–∞–∫–∂–µ —ç—Ç–æ –º–æ–∂–µ—Ç –±—ã—Ç—å —Å–≤—è–∑–∞–Ω–æ —Å —Ç–µ–º, —á—Ç–æ –¥–∞–Ω–Ω—ã–µ –æ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è –≤ –Æ–∂–Ω–æ–º –°—É–¥–∞–Ω–µ –Ω–µ —Å–æ–±–∏—Ä–∞—é—Ç—Å—è –∏–ª–∏ –Ω–µ–¥–æ—Å—Ç—É–ø–Ω—ã –∏–∑-–∑–∞ –æ—Å–æ–±–µ–Ω–Ω–æ—Å—Ç–µ–π —Å—Ç–∞—Ç–∏—Å—Ç–∏—á–µ—Å–∫–æ–≥–æ —É—á—ë—Ç–∞ –≤ —Å—Ç—Ä–∞–Ω–µ.

–ù–µ–ª—å–∑—è –∏—Å–∫–ª—é—á–∞—Ç—å, —á—Ç–æ –Ω–µ–∫–æ—Ç–æ—Ä—ã–µ —Å—Ç—Ä–∞–Ω—ã –º–æ–≥—É—Ç –∏–º–µ—Ç—å –Ω–µ–ø–æ–ª–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ –ø–æ –æ—Ç–¥–µ–ª—å–Ω—ã–º –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º, —á—Ç–æ —Å—Ç–æ–∏—Ç —É—á–∏—Ç—ã–≤–∞—Ç—å –ø—Ä–∏ –ø–æ—Å–ª–µ–¥—É—é—â–µ–º –∞–Ω–∞–ª–∏–∑–µ.

### 2

–î–ª—è –∫–∞–∂–¥–æ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞ –≤ —Ä–∞—Å—Å–º–∞—Ç—Ä–∏–≤–∞–µ–º—ã—Ö –¥–∞–Ω–Ω—ã—Ö —É–∫–∞–∂–∏—Ç–µ –≤–∏–¥ —ç—Ç–æ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞ –∏ –∫—Ä–∞—Ç–∫–æ –æ–±–æ—Å–Ω—É–π—Ç–µ, –ø–æ—á–µ–º—É –≤–∏–¥ –∏–º–µ–Ω–Ω–æ —Ç–∞–∫–æ–π.

# **–î–∞—Ç–∞—Å–µ—Ç drinks.csv:**

–ü—Ä–∏–∑–Ω–∞–∫–∏:

index - —Ç–µ—Ö–Ω–∏—á–µ—Å–∫–∏–π, –Ω—É–∂–µ–Ω –¥–ª—è –∏–Ω–¥–µ–∫—Å–∏—Ä–æ–≤–∞–Ω–∏—è —Å—Ç—Ä–æ–∫ –≤ —Ç–∞–±–ª–∏—Ü–µ, –Ω–∏–∫–∞–∫–æ–≥–æ –∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–æ–≥–æ —Å–º—ã—Å–ª–∞ –Ω–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è–µ—Ç

country - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –Ω–∞–∑–≤–∞–Ω–∏–µ —Å—Ç—Ä–∞–Ω—ã, –Ω–µ—É–ø–æ—Ä—è–¥–æ—á–µ–Ω–Ω–æ–µ –∫–æ–Ω–µ—á–Ω–æ–µ –º–Ω–æ–∂–µ—Å—Ç–≤–æ

beer_servings - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π (—á–∏—Å–ª–æ–≤–æ–π), –æ–±–æ–∑–Ω–∞—á–∞–µ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ—Ä—Ü–∏–π –ø–∏–≤–∞

spirit_servings - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π (—á–∏—Å–ª–æ–≤–æ–π), –æ–±–æ–∑–Ω–∞—á–∞–µ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ—Ä—Ü–∏–π –∫—Ä–µ–ø–∫–æ–≥–æ –∞–ª–∫–æ–≥–æ–ª

wine_servings - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π (—á–∏—Å–ª–æ–≤–æ–π), –æ–±–æ–∑–Ω–∞—á–∞–µ—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ—Ä—Ü–∏–π –≤–∏–Ω

total_litres_of_pure_alcohol - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π, –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ª–∏—Ç—Ä–æ–≤ —á–∏—Å—Ç–æ–≥–æ –∞–ª–∫–æ–≥–æ–ª—è –Ω–∞ 1 —á–µ–ª–æ–≤–µ–∫–∞


# **–î–∞—Ç–∞—Å–µ—Ç lifeexpectancy-verbose.csv:**

–ü—Ä–∏–∑–Ω–∞–∫–∏:

index - —Ç–µ—Ö–Ω–∏—á–µ—Å–∫–∏–π, –Ω—É–∂–µ–Ω –¥–ª—è –∏–Ω–¥–µ–∫—Å–∏—Ä–æ–≤–∞–Ω–∏—è —Å—Ç—Ä–æ–∫ –≤ —Ç–∞–±–ª–∏—Ü–µ, –Ω–∏–∫–∞–∫–æ–≥–æ –∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–æ–≥–æ —Å–º—ã—Å–ª–∞ –Ω–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è–µ—Ç

GhoCode	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –æ–±–æ–∑–Ω–∞—á–∞–µ—Ç —Ç–∏–ø –æ—Ç—á–µ—Ç–∞ –∏–ª–∏ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∏ –≤ –í–û–ó, –≤ –¥–∞–ª—å–Ω–µ–π—à–µ–º –º–æ–≥—É—Ç –ø–æ—è–≤–∏—Ç—å—Å—è –Ω–æ–≤—ã–µ —Ç–∏–ø—ã –æ—Ç—á–µ—Ç–æ–≤, –Ω–æ –≤—Å–µ —Ä–∞–≤–Ω–æ –±—É–¥–µ—Ç –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–º, —Ç–∞–∫ –∫–∞–∫ —ç—Ç–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã–µ –∫–æ–¥—ã —É—á–µ—Ç–∞ —Ä–∞–∑–Ω—ã—Ö —Ç–∏–ø–æ–≤ –æ—Ç—á–µ—Ç–æ–≤ –∏ –¥–æ–∫—É–º–µ–Ω—Ç–æ–≤

GhoDisplay - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, —Ç–µ–∫—Å—Ç–æ–≤–æ–µ –æ–ø–∏—Å–∞–Ω–∏–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è, –Ω–µ—É–ø–æ—Ä—è–¥–æ—á–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è, –∫–æ–Ω–µ—á–Ω–æ–µ –≤ –¥–∞–Ω–Ω—ã–π –º–æ–º–µ–Ω—Ç

PublishStateCode - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, —Ä–∞–∑–ª–∏—á–Ω—ã–µ —Å–æ—Å—Ç–æ—è–Ω–∏—è –ø—É–±–ª–∏–∫–∞—Ü–∏–∏, –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å–æ—Å—Ç–æ—è–Ω–∏–π –ø—É–±–ª–∏–∫–∞—Ü–∏–∏ (–≤ —ç—Ç–æ–º –¥–∞—Ç–∞—Å–µ—Ç–µ –Ω–µ –æ–±–Ω–∞—Ä—É–∂–µ–Ω–æ –∑–Ω–∞—á–µ–Ω–∏–π, –∫—Ä–æ–º–µ PUBLISHED, –Ω–æ –≤–µ—Ä–æ—è—Ç–Ω–æ –≤–æ–∑–º–æ–∂–Ω—ã –≤–∞—Ä–∏–∞–Ω—Ç—ã DRAFT, RETIRED –∏ —Ç. –¥.)

PublishStateDisplay	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –ø–æ–¥–æ–±–Ω—ã–π –ø—Ä–æ—à–ª–æ–º—É –ø—Ä–∏–∑–Ω–∞–∫—É, –Ω–æ –¥–ª—è –ø—Ä–æ—Å–º–æ—Ç—Ä–∞ –Ω–µ –∫–æ–º–ø—å—é—Ç–µ—Ä–∞, –∞ —á–µ–ª–æ–≤–µ–∫–∞ (–±–æ–ª–µ–µ –ø—Ä–∏–≤—ã—á–Ω—ã–µ —Å—Ç—Ä–æ—á–Ω—ã–µ –∏ –±–æ–ª—å—à–∏–µ, –º–µ–Ω—å—à–µ –ø—Ä–∞–≤–∏–ª –æ—Ç–æ–±—Ä–∞–∂–µ–Ω–∏—è)

YearCode - –ø–æ—Ä—è–¥–∫–æ–≤—ã–π, –µ—Å—Ç—å –µ—Å—Ç–µ—Å—Ç–≤–µ–Ω–Ω—ã–π —Ö—Ä–æ–Ω–æ–ª–æ–≥–∏—á–µ—Å–∫–∏–π –ø–æ—Ä—è–¥–æ–∫

YearDisplay	- –ø–æ—Ä—è–¥–∫–æ–≤—ã–π, —É–ø–æ—Ä—è–¥–æ—á–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≥–æ–¥–æ–≤, –Ω–æ –¥–ª—è —á—Ç–µ–Ω–∏—è —á–µ–ª–æ–≤–µ–∫–∞

RegionCode	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –∫–æ–¥ —Ä–µ–≥–∏–æ–Ω–∞ –±–µ–∑ —á–∏—Å–ª–æ–≤–æ–≥–æ —Å–º—ã—Å–ª–∞

RegionDisplay	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, —Ç–µ–∫—Å—Ç–æ–≤–æ–µ –Ω–∞–∑–≤–∞–Ω–∏–µ —Ä–µ–≥–∏–æ–Ω–∞ (–æ–ø—è—Ç—å –∂–µ —É–¥–æ–±–Ω—ã–π –¥–ª—è —á–µ–ª–æ–≤–µ–∫–∞)

WorldBankIncomeGroupGroupCode	- –ø–æ—Ä—è–¥–∫–æ–≤—ã–π, —É—Ä–æ–≤–Ω–∏ –¥–æ—Ö–æ–¥–∞ –≥–æ—Å—É–¥–∞—Ä—Å—Ç–≤–∞, —Å–æ–≥–ª–∞—Å–Ω–æ –¥–∞–Ω–Ω—ã–º –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞, –æ–Ω–∏ –∏–º–µ—é—Ç –µ—Å—Ç–µ—Å—Ç–≤–µ–Ω–Ω—ã–π –ø–æ—Ä—è–¥–æ–∫ (–æ—Ç –Ω–∏–∑–∫–æ–≥–æ –∫ –≤—ã—Å–æ–∫–æ–º—É –∏ –ø—Ä–æ—á–µ–µ), –º–Ω–æ–∂–µ—Å—Ç–≤–æ –∫–æ–Ω–µ—á–Ω–æ

WorldBankIncomeGroupDisplay	- –ø–æ—Ä—è–¥–∫–æ–≤—ã–π, —Ç–µ–∫—Å—Ç–æ–≤–æ–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–∏–µ –ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞

CountryCode	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –∫–æ–¥ —Å—Ç—Ä–∞–Ω—ã –±–µ–∑ —á–∏—Å–µ–ª, –±—É–∫–≤–µ–Ω–Ω—ã–π

CountryDisplay	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –Ω–∞–∑–≤–∞–Ω–∏–µ —Å—Ç—Ä–∞–Ω, –≤ –∫–∞–∫–æ–π-—Ç–æ –º–µ—Ä–µ —Ä–∞—Å—à–∏—Ñ—Ä–æ–≤–∫–∞ –∫–æ–¥–∞ (–ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞)

SexCode	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, –∫–æ–Ω–µ—á–Ω–æ–µ –º–Ω–æ–∂–µ—Å—Ç–≤–æ –∑–Ω–∞—á–µ–Ω–∏–π (MLE, FMLE, BTSX)

SexDisplay	- –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π, —Ç–µ–∫—Å—Ç–æ–≤–æ–µ –æ–ø–∏—Å–∞–Ω–∏–µ –ø–æ–ª–∞ (–ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞)

DisplayValue	- –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π, –∑–Ω–∞—á–µ–Ω–∏–µ —Ä–∞—Å—Å–º–∞—Ç—Ä–∏–≤–∞–µ–º–æ–≥–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è –≤ –æ—Ç—á–µ—Ç–µ (–æ—Ç–±—Ä–æ—à–µ–Ω–∞ –¥—Ä–æ–±–Ω–∞—è —á–∞—Å—Ç—å)

Numeric - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π, –ø—Ä–µ–¥—ã–¥—É—â–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ —á–∏—Å–ª–æ–≤–æ–º —Ñ–æ—Ä–º–∞—Ç–µ (—Å –¥—Ä–æ–±–Ω–æ–π —á–∞—Å—Ç—å—é)

### 3

–í–Ω–∏–º–∞—Ç–µ–ª—å–Ω–æ –∏–∑—É—á–∏—Ç–µ –ø—Ä–∏–∑–Ω–∞–∫–∏ –æ–±–µ–∏—Ö —Ç–∞–±–ª–∏—Ü. –ö–∞–∫ –≤—ã —Å—á–∏—Ç–∞–µ—Ç–µ, –∫–∞–∫–∞—è –∏–∑ —Ç–∞–±–ª–∏—Ü —è–≤–ª—è–µ—Ç—Å—è –≥–ª–∞–≤–Ω–æ–π (–∞ –∫–∞–∫–∞—è —Å–æ–ø—É—Ç—Å—Ç–≤—É—é—â–µ–π)? –ü–æ—á–µ–º—É –≤—ã —Ç–∞–∫ –¥—É–º–∞–µ—Ç–µ?

–ö–∞–∫–æ–π –ø—Ä–∏–∑–Ω–∞–∫ –º–æ–∂–µ—Ç –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è—Ç—å —Å—É—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π –∏–Ω—Ç–µ—Ä–µ—Å –¥–ª—è –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è –∏ —è–≤–ª—è—Ç—å—Å—è —Ü–µ–ª–µ–≤–æ–π –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π –≤ —Ä–∞–º–∫–∞—Ö –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–Ω–æ–≥–æ –¥–∞—Ç–∞—Å–µ—Ç–∞? –û—Ç–≤–µ—Ç –æ–±–æ—Å–Ω—É–π—Ç–µ.

***–ë–æ–Ω—É—Å (1 –±–æ–Ω. –±–∞–ª–ª):*** –ü–æ–ø—Ä–æ–±—É–π—Ç–µ –æ–ø–∏—Å–∞—Ç—å –∑–∞–¥–∞—á—É –º–∞—à–∏–Ω–Ω–æ–≥–æ –æ–±—É—á–µ–Ω–∏—è, –∫–æ—Ç–æ—Ä—É—é –≤—ã –º–æ–≥–ª–∏ –±—ã —Ä–µ—à–∞—Ç—å –¥–ª—è –¥–∞–Ω–Ω–æ–≥–æ –¥–∞—Ç–∞—Å–µ—Ç–∞ —Å —É—á–µ—Ç–æ–º –≤—ã–±—Ä–∞–Ω–Ω–æ–π –≤–∞–º–∏ —Ä–∞–Ω–Ω–µ–µ —Ü–µ–ª–µ–≤–æ–π –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π –∏ –ø—Ä–æ–±–ª–µ–º–∞—Ç–∏–∫–∏ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è. –ü–æ–¥—Ä–æ–±–Ω–µ–µ –ø—Ä–æ –ø–æ—Å—Ç–∞–Ω–æ–≤–∫—É –∏ —Ñ–æ—Ä–º–∞–ª–∏–∑–∞—Ü–∏—é –∑–∞–¥–∞—á –º–∞—à–∏–Ω–Ω–æ–≥–æ –æ–±—É—á–µ–Ω–∏—è, –∞ —Ç–∞–∫–∂–µ –ø—Ä–æ —Ä–∞–∑–ª–∏—á–Ω—ã–µ —Ç–∏–ø—ã —Ç–∞–∫–∏—Ö –∑–∞–¥–∞—á ‚Äî –≤—ã –º–æ–∂–µ—Ç–µ –ø—Ä–æ—á–∏—Ç–∞—Ç—å, –Ω–∞–ø—Ä–∏–º–µ—Ä, –≤–æ—Ç –≤ —ç—Ç–æ–π [—Å—Ç–∞—Ç—å–µ](https://habr.com/ru/company/simbirsoft/blog/565396/) (–≤ –Ω–∞—á–∞–ª–µ)

–ì–ª–∞–≤–Ω–æ–π —Ç–∞–±–ª–∏—Ü–µ–π —è–≤–ª—è–µ—Ç—Å—è —Ç–∞–±–ª–∏—Ü–∞ lifeexpectancy-verbose.csv, —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–µ–Ω–Ω–æ —Å–æ–ø—É—Å—Ç–≤—É—é—â–∞—è - drinks.csv. –¢–∞–∫ –∫–∞–∫ —Ç–∞–±–ª–∏—Ü–∞ –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∏–º–µ–µ—Ç –¥–µ—Ç–∞–ª–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ –∏–∑–º–µ—Ä–µ–Ω–∏—è –ø–æ –≥–æ–¥–∞–º, –ø–æ–ª—É –∏ —Ä–∞–∑–ª–∏—á–Ω—ã–º –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è–º, –∞ —Ç–∞–±–ª–∏—Ü–∞ –æ–± —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è —Å–æ–¥–µ—Ä–∂–∏—Ç –≤—Å–ø–æ–º–æ–≥–∞—Ç–µ–ª—å–Ω—ã–µ —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏ –ø–æ —Å—Ç—Ä–∞–Ω–µ, –æ–Ω–∞ —Ç–∞–∫–∂–µ –≤ –∫–∞–∫–æ–π-—Ç–æ —Å—Ç–µ–ø–µ–Ω–∏ –∞–≥—Ä–µ–≥–∏—Ä–æ–≤–∞–Ω–Ω–∞. –¢–∞–∫–∂–µ –Ω–∞—à–∞ —Ü–µ–ª—å - –∏–∑—É—á–∏—Ç—å –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –æ—Ç –Ω–µ–∫–æ—Ç–æ—Ä—ã—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤, –≤ —á–∞—Å—Ç–Ω–æ—Å—Ç–∏ –æ—Ç —É—Ä–æ–≤–Ω—è —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –≤ —Å—Ç—Ä–∞–Ω–µ, –ø–æ—ç—Ç–æ–º—É –¥–∞–Ω–Ω—ã–µ –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ - –≥–ª–∞–≤–Ω—ã–µ, –∞ –æ —É—Ä–æ–≤–Ω–µ —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è - –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–µ.

–£–∂–µ –Ω–µ–º–Ω–æ–≥–æ —Å–∫–∞–∑–∞–Ω–æ –≤ –ø—Ä–µ–¥—ã–¥—É—â–µ–º –∞–±–∑–∞—Ü–µ, –¥–æ–ø–æ–ª–Ω–∏–º. –°—É—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π –∏–Ω—Ç–µ—Ä–µ—Å —É –Ω–∞—Å –ø–æ—è–≤–ª—è–µ—Ç—Å—è –∫ –ø—Ä–∏–∑–Ω–∞–∫—É –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ (–∫–æ–ª–æ–Ω–∫–∏ DisplayValue –∏–ª–∏ Numeric). –≠—Ç–æ—Ç –ø–æ–∫–∞–∑–∞—Ç–µ–ª—å –º—ã —Ö–æ—Ç–∏–º –æ–±—ä—è—Å–Ω–∏—Ç—å –ª–∏–±–æ –ø—Ä–µ–¥—Å–∫–∞–∑–∞—Ç—å (—ç—Ç–æ —Å–ª–µ–¥—É—é—â–∏–π –≤–æ–ø—Ä–æ—Å:)) –≤ —Ç–æ–º —á–∏—Å–ª–µ —Å –ø–æ–º–æ—â—å—é –≤–Ω–µ—à–Ω–∏—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤ - —É—Ä–æ–≤–Ω—è —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è, –¥–æ—Ö–æ–¥–æ–≤ —Å—Ç—Ä–∞–Ω, –∞ —Ç–∞–∫–∂–µ —Ä–µ–≥–∏–æ–Ω –∏ –ø–æ–ª.

–¢–µ–ø–µ—Ä—å –ø–æ–≥–æ–≤–æ—Ä–∏–º –æ–± –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ–º. –ó–∞–¥–∞—á–µ–π –º–∞—à–∏–Ω–Ω–æ–≥–æ –æ–±—É—á–µ–Ω–∏—è –º–æ–∂–µ—Ç —è–≤–ª—è—Ç—å—Å—è –ø—Ä–µ–¥—Å–∫–∞–∑–∞–Ω–∏–µ –æ–∂–∏–¥–∞–µ–º–æ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ (—á—Ç–æ –æ—á–µ–Ω—å –≤–∞–∂–Ω–æ –¥–ª—è –ø–ª–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏—è —ç–∫–æ–Ω–æ–º–∏–∫–∏ —Å—Ç—Ä–∞–Ω—ã –Ω–∞ –±—É–¥—É—â–µ–µ) –æ—Ç –≤–Ω–µ—à–Ω–∏—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤ –¥–ª—è –∫–∞–∂–¥–æ–π —Å—Ç—Ä–∞–Ω—ã. –ù–∞ –≤—Ö–æ–¥ –ø–æ–¥–∞–µ—Ç—Å—è –≤–µ–∫—Ç–æ—Ä –ø—Ä–∏–∑–Ω–∞–∫–æ–≤ X = [–∞–ª–∫–æ–≥–æ–ª—å, —É—Ä–æ–≤–µ–Ω—å –¥–æ—Ö–æ–¥–æ–≤, –ø–æ–ª, –≥–æ–¥], –Ω–∞ –≤—ã—Ö–æ–¥–µ –ø–æ–ª—É—á–∞–µ–º –∑–Ω–∞—á–µ–Ω–∏–µ Y - –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏.

### 4

–ö–∞–∫–æ–≤–∞ –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ê—Ñ—Ä–∏–∫–µ? –ö–∞–∫–æ–≤–∞ –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º—É–∂—á–∏–Ω –∏ –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω —Å—Ä–µ–¥–∏ –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π –ø–æ –ê—Ñ—Ä–∏–∫–µ?

***–ë–æ–Ω—É—Å (2 –±–æ–Ω. –±–∞–ª–ª–∞):*** –°—Ä–∞–≤–Ω–∏—Ç–µ —ç—Ç–∏ –¥–æ–ª–∏ —Å –∞–Ω–∞–ª–æ–≥–∏—á–Ω—ã–º–∏ –¥–æ–ª—è–º–∏ –ø–æ –¥—Ä—É–≥–∏–º —Ä–µ–≥–∏–æ–Ω–∞–º. –ö–∞–∫ –≤—ã –º–æ–∂–µ—Ç–µ –æ–±—ä—è—Å–Ω–∏—Ç—å –≤–æ–∑–Ω–∏–∫–∞—é—â–∏–µ —Å—Ö–æ–¥—Å—Ç–≤–∞ –∏ —Ä–∞–∑–ª–∏—á–∏—è? –ü—Ä–æ–∫–æ–º–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ –ø–æ–ª—É—á–µ–Ω–Ω—ã–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã.

In [126]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ê—Ñ—Ä–∏–∫–µ
life_exp[life_exp['RegionDisplay'] == 'Africa'].shape[0] / life_exp.shape[0]

0.23782771535580524

In [127]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ê—Ñ—Ä–∏–∫–µ
cnt_africa = life_exp[life_exp['RegionDisplay'] == 'Africa'].shape[0]
cnt_africa

1524

In [128]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º—É–∂—á–∏–Ω –≤ –ê—Ñ—Ä–∏–∫–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_africa_male = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_africa_male / cnt_africa

0.3333333333333333

In [129]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –≤ –ê—Ñ—Ä–∏–∫–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_africa_female = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_africa_female / cnt_africa

0.3333333333333333

–û–∫–∞–∑–∞–ª–æ—Å—å, —á—Ç–æ —Å—É–º–º–∞ –¥–æ–ª–µ–π –ø–æ –º—É–∂—á–∏–Ω–∞–º –∏ –∂–µ–Ω—â–∏–Ω–∞–º –Ω–µ —Ä–∞–≤–Ω–∞ 1. –ü—Ä–∏ –≤–Ω–∏–º–∞—Ç–µ–ª—å–Ω–æ–º —Ä–∞—Å—Å–º–æ—Ç—Ä–µ–Ω–∏–∏ —Ç–∞–±–ª–∏—Ü—ã –º—ã –≤–∏–¥–∏–º, —á—Ç–æ –≤ –∫–æ–ª–æ–Ω–∫–µ SexDisplay –≤—Å—Ç—Ä–µ—á–∞—é—Ç—Å—è —Ç—Ä–∏ –∑–Ω–∞—á–µ–Ω–∏—è: Female, Male –∏ Both sexes. –°—Ç–∞—Ç—å–∏ —Å–æ –∑–Ω–∞—á–µ–Ω–∏–µ–º Both sexes –æ—Ç—Ä–∞–∂–∞—é—Ç —Å—Ç–∞—Ç—å–∏ –¥–ª—è –æ–±–æ–∏—Ö –ø–æ–ª–æ–≤, –ø–æ—ç—Ç–æ–º—É –∏—Ö –Ω—É–∂–Ω–æ —É—á–∏—Ç—ã–≤–∞—Ç—å –ø—Ä–∏ —Ä–∞—Å—Å—á–µ—Ç–µ –¥–æ–ª–µ–π –¥–ª—è –æ–±–µ–∏—Ö –≥—Ä—É–ø–ø. –î–ª—è –∞–Ω–∞–ª–∏–∑–∞ –º–æ–∂–Ω–æ –ª–∏–±–æ —É—á–∏—Ç—ã–≤–∞—Ç—å —Å—Ç–∞—Ç—å–∏ –¥–ª—è –æ–±–æ–∏—Ö –ø–æ–ª–æ–≤ –≤ –¥–æ–ª—è—Ö –º—É–∂—á–∏–Ω –∏ –∂–µ–Ω—â–∏–Ω, –∞ –º–æ–∂–Ω–æ –æ—Ç–¥–µ–ª—å–Ω–æ –ø–æ—Å—á–∏—Ç–∞—Ç—å –¥–æ–ª—é —Å—Ç–∞—Ç–µ–π –¥–ª—è –æ–±–æ–∏—Ö –ø–æ–ª–æ–≤

In [130]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π —Å –æ–±–æ–∏–º–∏ –ø–æ–ª–∞–º–∏ –≤ –ê—Ñ—Ä–∏–∫–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_africa_both = life_exp[(life_exp['RegionDisplay'] == 'Africa') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_africa_both / cnt_africa

0.3333333333333333

–î–∞, —Ç–µ–ø–µ—Ä—å –≤ —Å—É–º–º–µ –ø–æ–ª—É—á–∞–µ—Ç—Å—è 1. –ó–Ω–∞—á–∏—Ç –º—ã –∫–æ—Ä—Ä–µ–∫–Ω–æ –≤—ã–≤–µ–ª–∏ –¥–æ–ª–∏ –¥–ª—è –∫–∞–∂–¥—ã—Ö –≤–∞—Ä–∏–∞–Ω—Ç–æ–≤ –∑–Ω–∞—á–µ–Ω–∏–π –∫–æ–ª–æ–Ω–∫–∏ –ø–æ–ª–∞. –í—Å–µ —ç—Ç–∏ –¥–æ–ª–∏ —Ä–∞–≤–Ω—ã, –ø–æ—ç—Ç–æ–º—É –¥–µ–ª–∞–µ–º –Ω–µ–±–µ–∑–æ—Å–Ω–æ–≤–∞—Ç–µ–ª—å–Ω–æ–µ –ø—Ä–µ–¥–ø–æ–ª–æ–∂–µ–Ω–∏–µ (–Ω–∞ –æ—Å–Ω–æ–≤–µ –∞—Ä–∏—Ñ–º–µ—Ç–∏–∫–∏), —á—Ç–æ –ø—Ä–∏ —É—á–µ—Ç–µ —Å—Ç–∞—Ç–µ–π —Å –æ–±–æ–∏–º–∏ –ø–æ–ª–∞–º–∏ –¥–æ–ª—è –º—É–∂—á–∏–Ω –∏ –∂–µ–Ω—â–∏–Ω - 1 –∫ 1. –ü—Ä–æ–≤–µ—Ä–∏–º —Å –ø–æ–º–æ—â—å—é –∫–æ–¥–∞.

In [131]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –º—É–∂—á–∏–Ω—ã:
(cnt_africa_male + cnt_africa_both) / (cnt_africa + cnt_africa_both)

0.5

In [132]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –∂–µ–Ω—â–∏–Ω—ã:
(cnt_africa_female + cnt_africa_both) / (cnt_africa + cnt_africa_both)

0.5

–¢–µ–ø–µ—Ä—å –ø–æ—Å–º–æ—Ç—Ä–∏–º –ø–æ –¥—Ä—É–≥–∏–º —Ä–µ–≥–∏–æ–Ω–∞–º:

–ï–≤—Ä–æ–ø–∞:

In [133]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ï–≤—Ä–æ–ø–µ
life_exp[(life_exp['RegionDisplay'] == 'Europe')].shape[0] / life_exp.shape[0]

0.272940074906367

In [134]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ï–≤—Ä–æ–ø–µ
cnt_europe = life_exp[life_exp['RegionDisplay'] == 'Europe'].shape[0]
cnt_europe

1749

In [135]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –≤ –ï–≤—Ä–æ–ø–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_europe_female = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_europe_female / cnt_europe

0.3333333333333333

In [136]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º—É–∂—á–∏–Ω –≤ –ï–≤—Ä–æ–ø–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_europe_male = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_europe_male / cnt_europe

0.3333333333333333

In [137]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π —Å –æ–±–æ–∏–º–∏ –ø–æ–ª–∞–º–∏ –≤ –ï–≤—Ä–æ–ø–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_europe_both = life_exp[(life_exp['RegionDisplay'] == 'Europe') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_europe_both / cnt_europe

0.3333333333333333

In [138]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –∂–µ–Ω—â–∏–Ω—ã:
(cnt_europe_female + cnt_europe_both) / (cnt_europe + cnt_europe_both)

0.5

In [139]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –º—É–∂—á–∏–Ω—ã:
(cnt_europe_male + cnt_europe_both) / (cnt_europe + cnt_europe_both)

0.5

–ö–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å–æ–≤–ø–∞–¥–∞–µ—Ç —Ç–æ—á—å-–≤-—Ç–æ—á—å. –ü–æ—Å–º–æ—Ç—Ä–∏–º –Ω–∞ —Ä–µ–≥–∏–æ–Ω Western Pacific

In [140]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–æ–º —Ä–µ–≥–∏–æ–Ω–µ
life_exp[life_exp['RegionDisplay'] == 'Western Pacific'].shape[0] / life_exp.shape[0]

0.13904494382022473

In [141]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤ –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–æ–º —Ä–µ–≥–∏–æ–Ω–µ
cnt_west_pacific = life_exp[life_exp['RegionDisplay'] == 'Western Pacific'].shape[0]
cnt_west_pacific

891

In [142]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –≤ –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–æ–º —Ä–µ–≥–∏–æ–Ω–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_west_pacific_female = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Female')].shape[0]
cnt_west_pacific_female / cnt_west_pacific

0.3333333333333333

In [143]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º—É–∂—á–∏–Ω –≤ –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–æ–º —Ä–µ–≥–∏–æ–Ω–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_west_pacific_male = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Male')].shape[0]
cnt_west_pacific_male / cnt_west_pacific

0.3333333333333333

In [144]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π —Å –æ–±–æ–∏–º–∏ –ø–æ–ª–∞–º–∏ –≤ –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–æ–º —Ä–µ–≥–∏–æ–Ω–µ –æ—Ç –≤—Å–µ—Ö —Å—Ç–∞—Ç–µ–π
cnt_west_pacific_both = life_exp[(life_exp['RegionDisplay'] == 'Western Pacific') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]
cnt_west_pacific_both / cnt_west_pacific

0.3333333333333333

In [145]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –∂–µ–Ω—â–∏–Ω—ã:
(cnt_west_pacific_female + cnt_west_pacific_both) / (cnt_west_pacific + cnt_west_pacific_both)

0.5

In [146]:
# –¥–æ–ª—è —Å—Ç–∞—Ç–µ–π –≥–¥–µ —É–ø–æ–º–∏–Ω–∞—é—Ç—Å—è –º—É–∂—á–∏–Ω—ã:
(cnt_west_pacific_male + cnt_west_pacific_both) / (cnt_west_pacific + cnt_west_pacific_both)

0.5

–ß—Ç–æ –≤ –∏—Ç–æ–≥–µ? –ê–Ω–∞–ª–æ–≥–∏—á–Ω—ã–µ –¥–æ–ª–∏ –Ω–∞–±–ª—é–¥–∞—é—Ç—Å—è –∏ –≤ –¥—Ä—É–≥–∏—Ö —Ä–µ–≥–∏–æ–Ω–∞—Ö. –≠—Ç–æ –æ–±—ä—è—Å–Ω—è–µ—Ç—Å—è —Ç–µ–º, —á—Ç–æ —Å—Ç—Ä—É–∫—Ç—É—Ä–∞ –æ—Ç—á—ë—Ç–Ω—ã—Ö –¥–∞–Ω–Ω—ã—Ö –í–û–ó –µ–¥–∏–Ω–æ–æ–±—Ä–∞–∑–Ω–∞: –¥–ª—è –∫–∞–∂–¥–æ–≥–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è –ø—É–±–ª–∏–∫—É—é—Ç—Å—è —Å–≤–µ–¥–µ–Ω–∏—è –ø–æ —Ç—Ä—ë–º –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º –ø–æ–ª–∞ ‚Äî Male, Female –∏ Both sexes. –ü–æ—ç—Ç–æ–º—É —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –ø–æ –ø–æ–ª—É –æ—Å—Ç–∞—ë—Ç—Å—è –æ–¥–∏–Ω–∞–∫–æ–≤—ã–º –¥–ª—è –≤—Å–µ—Ö —Ä–µ–≥–∏–æ–Ω–æ–≤ –∏ –Ω–µ –æ—Ç—Ä–∞–∂–∞–µ—Ç —Ñ–∞–∫—Ç–∏—á–µ—Å–∫–∏—Ö —Ä–∞–∑–ª–∏—á–∏–π, –∞ –ª–∏—à—å —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω—É—é —Å—Ö–µ–º—É –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–∏—è –¥–∞–Ω–Ω—ã—Ö.

In [147]:
life_exp.groupby('RegionDisplay')['CountryDisplay'].nunique()

RegionDisplay
Africa                   47
Americas                 35
Eastern Mediterranean    22
Europe                   53
South_East Asia          11
Western Pacific          27
Name: CountryDisplay, dtype: int64

–†–∞–∑–ª–∏—á–∏—è –≤ –¥–æ–ª—è—Ö —Ä–µ–≥–∏–æ–Ω–æ–≤ –æ–±—ä—è—Å–Ω—è—é—Ç—Å—è —Ä–∞–∑–Ω—ã–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ–º —Å—Ç—Ä–∞–Ω, –≤—Ö–æ–¥—è—â–∏—Ö –≤ –∫–∞–∂–¥—ã–π —Ä–µ–≥–∏–æ–Ω –í–û–ó. –ï–≤—Ä–æ–ø–∞ –∏ –ê—Ñ—Ä–∏–∫–∞ –≤–∫–ª—é—á–∞—é—Ç –±–æ–ª—å—à–µ –≥–æ—Å—É–¥–∞—Ä—Å—Ç–≤, –ø–æ—ç—Ç–æ–º—É –Ω–∞ –Ω–∏—Ö –ø—Ä–∏—Ö–æ–¥–∏—Ç—Å—è –±–æ–ª—å—à–µ –∑–∞–ø–∏—Å–µ–π –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ. –ó–∞–ø–∞–¥–Ω–æ-–¢–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–∏–π —Ä–µ–≥–∏–æ–Ω —Å–æ–¥–µ—Ä–∂–∏—Ç –º–µ–Ω—å—à–µ —Å—Ç—Ä–∞–Ω, —á—Ç–æ –ø—Ä–∏–≤–æ–¥–∏—Ç –∫ –º–µ–Ω—å—à–µ–π –¥–æ–ª–µ —Å—Ç–∞—Ç–µ–π.

### 5

–°–∫–æ–ª—å–∫–æ –≤—Å–µ–≥–æ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç –≤–∏–¥–æ–≤ —Å—Ç–∞—Ç–µ–π —Å —Ç–æ—á–∫–∏ –∑—Ä–µ–Ω–∏—è –æ—Ü–µ–Ω–∏–≤–∞–µ–º–æ–≥–æ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏? –ö–∞–∫–æ–π –∏–∑ —ç—Ç–∏—Ö –≤–∏–¥–æ–≤ —Å—Ç–∞—Ç–µ–π —Å–∞–º—ã–π –ø–æ–ø—É–ª—è—Ä–Ω—ã–π (–Ω–∞–ø–∏—Å–∞–Ω–æ –Ω–∞–∏–±–æ–ª—å—à–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–∞—É—á–Ω—ã—Ö —Ä–∞–±–æ—Ç)? –í —Ä–∞–º–∫–∞—Ö –Ω–∞–π–¥–µ–Ω–Ω–æ–≥–æ –≤–∞–º–∏ —Å–∞–º–æ–≥–æ –ø–æ–ø—É–ª—è—Ä–Ω–æ–≥–æ –≤–∏–¥–∞ —Å—Ç–∞—Ç–µ–π –ø—Ä–æ–≤–µ–¥–∏—Ç–µ —Å—Ä–∞–≤–Ω–µ–Ω–∏–µ, –æ—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω–æ –∫–∞–∫–æ–π –∏–∑ –ø–æ–ª–æ–≤—ã—Ö –≥—Ä—É–ø–ø: –º—É–∂—á–∏–Ω—ã, –∂–µ–Ω—â–∏–Ω—ã –∏–ª–∏ –∂–µ –æ–±–∞ –ø–æ–ª–∞ ‚Äî —Å—Ç–∞—Ç–µ–π –≤ –Ω–µ–º –±—ã–ª–æ –±–æ–ª—å—à–µ –≤—Å–µ–≥–æ?

In [148]:
# –≤–∏–¥—ã —Å—Ç–∞—Ç–µ–π —á–µ—Ä–µ–∑ —Å—Ç–æ–ª–±–∏–∫ GhoDisplay
life_exp['GhoDisplay'].unique()

array(['Life expectancy at birth (years)',
       'Healthy life expectancy (HALE) at birth (years)',
       'Life expectancy at age 60 (years)'], dtype=object)

In [149]:
# –∏—Ö –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —á–µ—Ä–µ–∑ —Å—Ç–æ–ª–±–∏–∫ GhoDisplay
life_exp['GhoDisplay'].nunique()

3

In [150]:
# –≤–∏–¥—ã —Å—Ç–∞—Ç–µ–π —á–µ—Ä–µ–∑ —Å—Ç–æ–ª–±–∏–∫ GhoCode
life_exp['GhoCode'].unique()

array(['WHOSIS_000001', 'WHOSIS_000002', 'WHOSIS_000015'], dtype=object)

In [151]:
# –∏—Ö –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —á–µ—Ä–µ–∑ —Å—Ç–æ–ª–±–∏–∫ GhoCode
life_exp['GhoCode'].nunique()

3

In [152]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç–∞—Ç–µ–π –Ω–∞ –∫–∞–∂–¥—É—é –∫–∞—Ç–µ–≥–æ—Ä–∏—é
life_exp['GhoDisplay'].value_counts()

GhoDisplay
Life expectancy at birth (years)                   2328
Life expectancy at age 60 (years)                  2328
Healthy life expectancy (HALE) at birth (years)    1752
Name: count, dtype: int64

–°–∞–º—ã–º–∏ –ø–æ–ø—É–ª—è—Ä–Ω—ã–º–∏ –æ–∫–∞–∑–∞–ª–∏—Å—å —Å—Ç–∞—Ç—å–∏ Life expectancy at birth (years)	2328 —Å—Ç—Ä–æ–∫ –∏ Life expectancy at age 60 (years) - —Ç–æ–∂–µ 2328 —Å—Ç—Ä–æ–∫

In [153]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at birth (years) –æ –º—É–∂—á–∏–Ω–∞—Ö
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Male')].shape[0]

776

In [154]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at birth (years) –æ –∂–µ–Ω—â–∏–Ω–∞—Ö
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Female')].shape[0]

776

In [155]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at birth (years) –æ –æ–±–æ–∏—Ö –ø–æ–ª–æ–≤
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at birth (years)') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]

776

In [156]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at age 60 (years) –æ –º—É–∂—á–∏–Ω–∞—Ö
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Male')].shape[0]

776

In [157]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at age 60 (years) –æ –∂–µ–Ω—â–∏–Ω–∞—Ö
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Female')].shape[0]

776

In [158]:
# —Å—Ç–∞—Ç—å–∏ Life expectancy at age 60 (years) –æ–± –æ–±–æ–∏—Ö –ø–æ–ª–∞—Ö
life_exp[(life_exp['GhoDisplay'] == 'Life expectancy at age 60 (years)') & (life_exp['SexDisplay'] == 'Both sexes')].shape[0]

776

–°–∞–º—ã–º–∏ –ø–æ–ø—É–ª—è—Ä–Ω—ã–º–∏ –æ–∫–∞–∑–∞–ª–∏—Å—å —Å—Ç–∞—Ç—å–∏ –ø–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è–º Life expectancy at birth (years) –∏ Life expectancy at age 60 (years), –ø—Ä–∏ —ç—Ç–æ–º –∏—Ö –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–µ ‚Äî –ø–æ 2328 –∑–∞–ø–∏—Å–µ–π –∫–∞–∂–¥–∞—è. –ï—Å–ª–∏ —Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –ø–æ –ø–æ–ª—É –≤ —Ä–∞–º–∫–∞—Ö –≤—ã–±—Ä–∞–Ω–Ω–æ–≥–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è, —Ç–æ –¥–ª—è –º—É–∂—á–∏–Ω, –∂–µ–Ω—â–∏–Ω –∏ –æ–±–æ–∏—Ö –ø–æ–ª–æ–≤ —Å—Ç–∞—Ç—å–∏ —Ç–æ–∂–µ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω—ã –æ–¥–∏–Ω–∞–∫–æ–≤–æ ‚Äî –ø–æ 776 –∑–∞–ø–∏—Å–µ–π –Ω–∞ –∫–∞–∂–¥—É—é –∫–∞—Ç–µ–≥–æ—Ä–∏—é. –≠—Ç–æ –æ–±—ä—è—Å–Ω—è–µ—Ç—Å—è —Ç–µ–º, —á—Ç–æ —Å—Ç—Ä—É–∫—Ç—É—Ä–∞ —Ç–∞–±–ª–∏—Ü—ã –í–û–ó —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∏–∑–∏—Ä–æ–≤–∞–Ω–∞: –¥–ª—è –∫–∞–∂–¥–æ–≥–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è –ø—É–±–ª–∏–∫—É—é—Ç—Å—è –¥–∞–Ω–Ω—ã–µ –ø–æ –≤—Å–µ–º —Ç—Ä—ë–º –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º –ø–æ–ª–∞. –ü–æ—ç—Ç–æ–º—É –∑–¥–µ—Å—å –º—ã –≤–∏–¥–∏–º —Ä–∞–≤–Ω–æ–º–µ—Ä–Ω–æ–µ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –ø–æ –ø–æ–ª—É, –∞ —Ä–µ–∞–ª—å–Ω—ã–µ —Ä–∞–∑–ª–∏—á–∏—è –º–µ–∂–¥—É –ø–æ–ª–∞–º–∏ –∏–∑ —ç—Ç–∏—Ö –¥–∞–Ω–Ω—ã—Ö –Ω–µ –ø—Ä–æ—Å–ª–µ–∂–∏–≤–∞—é—Ç—Å—è.

### 6

–í—ã–≤–µ–¥–∏—Ç–µ –º–∏–Ω–∏–º–∞–ª—å–Ω—É—é, —Å—Ä–µ–¥–Ω—é—é, –º–µ–¥–∏–∞–Ω–Ω—É—é –∏ –º–∞–∫—Å–∏–º–∞–ª—å–Ω—É—é –æ—Ü–µ–Ω–µ–Ω–Ω—É—é –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –ª—é–¥–µ–π –æ—Ç —Ä–æ–∂–¥–µ–Ω–∏—è (`life expectancy at birth`). –í—ã–±–µ—Ä–∏—Ç–µ –ª—é–±—ã–µ —Ç—Ä–∏ —Å—Ç—Ä–∞–Ω—ã –Ω–∞ –≤–∞—à –≤–∫—É—Å –∏ –ø—Ä–æ–¥–µ–ª–∞–π—Ç–µ —Ç–æ –∂–µ —Å–∞–º–æ–µ —Ç–æ–ª—å–∫–æ –¥–ª—è —Å—Ç–∞—Ç–µ–π –ø–æ —ç—Ç–∏–º —Å—Ç—Ä–∞–Ω–∞–º. –ß—Ç–æ –º–æ–∂–Ω–æ —Å–∫–∞–∑–∞—Ç—å –Ω–∞ –æ—Å–Ω–æ–≤–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤, –∫–æ—Ç–æ—Ä—ã–µ –≤—ã –ø–æ–ª—É—á–∏–ª–∏?

In [159]:
# –º–∏–Ω–∏–º–∞–ª—å–Ω–∞—è, —Å—Ä–µ–¥–Ω—è—è, –º–µ–¥–∏–∞–Ω–Ω–∞—è, –º–∞–∫—Å–∏–º–∞–ª—å–Ω–∞—è –æ—Ü–µ–Ω–µ–Ω–Ω–∞—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –æ—Ç—á–µ—Ç–æ–≤ Life expectancy at birth (years)
life_birth = life_exp[life_exp['GhoCode'] == 'WHOSIS_000001']
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(38.0, np.float64(68.44137943298968), 70.857895, 87.15457)

In [160]:
# –î–ª—è –Ø–ø–æ–Ω–∏–∏:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Japan')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(76.0, np.float64(81.92561), 81.5, 87.15457)

In [161]:
# –î–ª—è –ù–∏–µ–≥—Ä–∏–∏:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Nigeria')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(45.0, np.float64(50.47333750000001), 50.5, 55.40039)

In [162]:
# –î–ª—è –ë—Ä–∞–∑–∏–ª–∏–∏:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Brazil')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(63.0, np.float64(71.46481583333333), 71.305075, 78.79631)

In [163]:
# –î–ª—è –†–æ—Å—Å–∏–∏:
life_birth = life_exp[(life_exp[('GhoCode')] == 'WHOSIS_000001') & (life_exp['CountryDisplay'] == 'Russian Federation')]
life_birth['Numeric'].min(), life_birth['Numeric'].mean(), life_birth['Numeric'].median(), life_birth['Numeric'].max()

(59.0, np.float64(68.07878416666667), 69.0, 75.22597)

–ò–∑ —ç—Ç–∏—Ö –¥–∞–Ω–Ω—ã—Ö –≤–∏–¥–Ω–æ, —á—Ç–æ –º–µ–∂–¥—É —Å—Ç—Ä–∞–Ω–∞–º–∏ —Å—É—â–µ—Å—Ç–≤—É—é—Ç –∑–Ω–∞—á–∏—Ç–µ–ª—å–Ω—ã–µ —Ä–∞–∑–ª–∏—á–∏—è –≤ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏. –í —Å—Ç—Ä–∞–Ω–∞—Ö —Å —Ä–∞–∑–≤–∏—Ç–æ–π –º–µ–¥–∏—Ü–∏–Ω–æ–π –∏ –≤—ã—Å–æ–∫–∏–º —É—Ä–æ–≤–Ω–µ–º –∂–∏–∑–Ω–∏ (–Ω–∞–ø—Ä–∏–º–µ—Ä, –Ø–ø–æ–Ω–∏—è) –ª—é–¥–∏ –∂–∏–≤—É—Ç –∑–Ω–∞—á–∏—Ç–µ–ª—å–Ω–æ –¥–æ–ª—å—à–µ, —á–µ–º –≤ —Å—Ç—Ä–∞–Ω–∞—Ö —Å –Ω–∏–∑–∫–∏–º —É—Ä–æ–≤–Ω–µ–º –∂–∏–∑–Ω–∏ –∏–ª–∏ –≤—ã—Å–æ–∫–∏–º —É—Ä–æ–≤–Ω–µ–º –∑–∞–±–æ–ª–µ–≤–∞–Ω–∏–π (–Ω–∞–ø—Ä–∏–º–µ—Ä, –ù–∏–≥–µ—Ä–∏—è). –ë—Ä–∞–∑–∏–ª–∏—è –ø–æ–∫–∞–∑—ã–≤–∞–µ—Ç –ø—Ä–æ–º–µ–∂—É—Ç–æ—á–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è, —á—Ç–æ –æ—Ç—Ä–∞–∂–∞–µ—Ç —Å–º–µ—à–∞–Ω–Ω—ã–π —É—Ä–æ–≤–µ–Ω—å —ç–∫–æ–Ω–æ–º–∏—á–µ—Å–∫–æ–≥–æ –∏ —Å–æ—Ü–∏–∞–ª—å–Ω–æ–≥–æ —Ä–∞–∑–≤–∏—Ç–∏—è.

### 7

–°—Ñ–æ—Ä–º–∏—Ä—É–π—Ç–µ —Ä–µ–∑—É–ª—å—Ç–∏—Ä—É—é—â–∏–π –¥–∞—Ç–∞—Ñ—Ä–µ–π–º –Ω–∞ –æ—Å–Ω–æ–≤–µ –ø—Ä–æ–¥–µ–ª–∞–Ω–Ω—ã—Ö –≤–∞–º–∏ –¥–µ–π—Å—Ç–≤–∏–π –≤ –ø—Ä–µ–¥—ã–¥—É—â–µ–º –Ω–æ–º–µ—Ä–µ. –£ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º–∞ –¥–æ–ª–∂–Ω–æ –±—ã—Ç—å 4 —Å—Ç–æ–ª–±—Ü–∞, –≤ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–∏–∏ —Å –∑–∞–¥–∞–Ω–Ω—ã–º–∏ –∞–≥—Ä–µ–≥–≥–∏—Ä—É—é—â–∏–º–∏ —Ñ—É–Ω–∫—Ü–∏—è–º–∏: –º–∏–Ω–∏–º—É–º, —Å—Ä–µ–¥–Ω–µ–µ, –º–µ–¥–∏–∞–Ω–∞, –º–∞–∫—Å–∏–º—É–º, ‚Äî –∞ —Ç–∞–∫–∂–µ 4 —Å—Ç—Ä–æ–∫–∏: —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –ø–æ –≤—Å–µ–º—É –¥–∞—Ç–∞—Å–µ—Ç—É; —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –ø–æ —Ç—Ä–µ–º –≤—ã–±—Ä–∞–Ω–Ω—ã–º –≤–∞–º–∏ —Å—Ç—Ä–∞–Ω–∞–º. –°–æ—Ö—Ä–∞–Ω–∏—Ç–µ –ø—Ä–æ–≥—Ä–∞–º–º–Ω–æ —Å–æ–∑–¥–∞–Ω–Ω—ã–π –≤–∞–º–∏ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º –≤ –≤–∏–¥–µ csv —Ñ–∞–π–ª–∞.

*–ü—Ä–∏–º–µ—á–∞–Ω–∏–µ. –î–∞—Ç–∞—Ñ—Ä–µ–π–º –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —Å–æ–∑–¥–∞–≤–∞—Ç—å –∞–≤—Ç–æ–º–∞—Ç–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω—ã–º –æ–±—Ä–∞–∑–æ–º. –ù–µ –¥–æ–ø—É—Å–∫–∞–µ—Ç—Å—è —Ä—É—á–Ω–æ–π –ø–µ—Ä–µ–Ω–æ—Å –∑–Ω–∞—á–µ–Ω–∏–π –∏–∑ –ø–æ–ª—É—á–µ–Ω–Ω—ã—Ö –≤ –ø—Ä–µ–¥—ã–¥—É—â–µ–º –∑–∞–¥–∞–Ω–∏–∏ —è—á–µ–µ–∫ –≤ –ø—É—Å—Ç–æ–π –¥–∞—Ç–∞—Ñ—Ä–µ–π–º –∏/–∏–ª–∏ –ø—Ä–æ–ø–∏—Å—ã–≤–∞–Ω–∏–µ –∫–æ–Ω–∫—Ä–µ—Ç–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π (—á–∏—Å–µ–ª) –≤ –∫–æ–¥–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã. –ü—Ä–µ–¥—Å—Ç–∞–≤—å—Ç–µ, —á—Ç–æ —É –Ω–∞—Å –Ω–µ 3 —Å—Ç—Ä–∞–Ω—ã, –∞ 100 –∏ –Ω–µ 4 –∞–≥—Ä–µ–≥–≥–∏—Ä—É—é—â–∏—Ö –º–µ—Ç—Ä–∏–∫–∏, –∞ 100!*

In [164]:
result_life_birth = life_exp[life_exp['GhoCode'] == 'WHOSIS_000001']
countries = ['Japan', 'Nigeria', 'Brazil']
country_info = result_life_birth[result_life_birth['CountryDisplay'].isin(countries)].groupby('CountryDisplay')['Numeric'].agg(–º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ='min', —Å—Ä–µ–¥–Ω–µ–µ='mean', –º–µ–¥–∏–∞–Ω–∞='median', –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ='max')
world_stats = result_life_birth['Numeric'].agg(–º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ='min', —Å—Ä–µ–¥–Ω–µ–µ='mean', –º–µ–¥–∏–∞–Ω–∞='median', –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ='max').to_frame().T
world_stats.index = ['World']
agg_df = pd.concat([world_stats, country_info])
agg_df.to_csv('life_expectancy_summary.csv')
agg_df

         –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ    —Å—Ä–µ–¥–Ω–µ–µ    –º–µ–¥–∏–∞–Ω–∞  –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ
World           38.0  68.441379  70.857895      87.15457
Brazil          63.0  71.464816  71.305075      78.79631
Japan           76.0  81.925610  81.500000      87.15457
Nigeria         45.0  50.473338  50.500000      55.40039

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_frame.html

### 8

–ï—Å—Ç—å –ª–∏ –≤ –Ω–∞—à–∏—Ö –¥–∞—Ç–∞—Å–µ—Ç–∞—Ö –ø—Ä–æ–ø—É—Å–∫–∏? –ï—Å–ª–∏ –¥–∞, —Ç–æ –≤ –∫–∞–∫–∏—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö? –°–∫–æ–ª—å–∫–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –∫–∞–∂–¥–æ–º –∏–∑ –Ω–∏—Ö?

–ü–æ–¥—É–º–∞–π—Ç–µ, –∫–∞–∫ —Å—Ç–æ–∏—Ç –∏–∑–±–∞–≤–∏—Ç—å—Å—è –æ—Ç –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –∫–∞–∂–¥–æ–º –∏–∑ —Å—Ç–æ–ª–±—Ü–æ–≤, –∏ —Å–¥–µ–ª–∞–π—Ç–µ —ç—Ç–æ. –ê—Ä–≥—É–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ –≤–∞—à–∏ –¥–µ–π—Å—Ç–≤–∏—è.

–ü—Ä–æ–≤–µ—Ä—å—Ç–µ, —á—Ç–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –Ω–∏–≥–¥–µ –Ω–µ –æ—Å—Ç–∞–ª–æ—Å—å.

*–ü—Ä–∏–º–µ—á–∞–Ω–∏–µ. –ù–µ –∑–∞–±—É–¥—å—Ç–µ —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –≤—Å–µ –∏–∑–º–µ–Ω–µ–Ω–∏—è! –í –ø–æ—Å–ª–µ–¥—É—é—â–∏—Ö –∑–∞–¥–∞–Ω–∏—è—Ö –≤—ã –¥–æ–ª–∂–Ω—ã —Ä–∞–±–æ—Ç–∞—Ç—å —Å —É–∂–µ –æ–±–Ω–æ–≤–ª–µ–Ω–Ω—ã–º–∏ –¥–∞—Ç–∞—Å–µ—Ç–∞–º–∏.*

In [165]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ —Ç–∞–±–ª–∏—Ü–µ drinks.csv
drinks.isna().sum()

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
dtype: int64

In [166]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ —Ç–∞–±–ª–∏—Ü–µ lifeexpectancy-verbose.csv
life_exp.isna().sum()

index                               0
GhoCode                             0
GhoDisplay                          0
PublishStateCode                    0
PublishStateDisplay                 0
YearCode                            0
YearDisplay                         0
RegionCode                          0
RegionDisplay                       0
WorldBankIncomeGroupGroupCode    1164
WorldBankIncomeGroupDisplay      1164
CountryCode                         0
CountryDisplay                      0
SexCode                             0
SexDisplay                          0
DisplayValue                        0
Numeric                             0
dtype: int64

In [167]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ —Ç–∞–±–ª–∏—Ü–µ life_expectancy_summary.csv
agg_df.isna().sum()

–º–∏–Ω–∏–º–∞–ª—å–Ω–æ–µ     0
—Å—Ä–µ–¥–Ω–µ–µ         0
–º–µ–¥–∏–∞–Ω–∞         0
–º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ    0
dtype: int64

–ü—Ä–æ–ø—É—Å–∫–∏ –¥–∞–Ω–Ω—ã—Ö –Ω–∞–±–ª—é–¥–∞—é—Ç—Å—è –≤ —Ç–∞–±–ª–∏—Ü–µ lifeexpectancy-verbose.csv –≤ –∫–æ–ª–æ–Ω–∫–∞—Ö WorldBankIncomeGroupGroupCode	- 1164 –ø—Ä–æ–ø—É—Å–∫–∞ –∏
WorldBankIncomeGroupDisplay - —Ç–∞–∫–∂–µ 1164 –ø—Ä–æ–ø—É—Å–∫–∞

In [168]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –ø–æ —Ä–µ–≥–∏–æ–Ω–∞–º –≤ —Ç–∞–±–ª–∏—Ü–µ lifeexpectancy-verbose.csv
life_exp['WorldBankIncomeGroupGroupCode'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   282
Americas                 210
Eastern Mediterranean    126
Europe                   318
South_East Asia           66
Western Pacific          162
Name: WorldBankIncomeGroupGroupCode, dtype: int64

In [169]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   282
Americas                 210
Eastern Mediterranean    126
Europe                   318
South_East Asia           66
Western Pacific          162
Name: WorldBankIncomeGroupDisplay, dtype: int64

In [170]:
# –≤—Å–µ–≥–æ –∑–∞–ø–∏—Å–µ–π
life_exp.shape[0]

6408

In [171]:
# –¥–æ–ª—è –ø—Ä–æ–ø—É—Å–∫–æ–≤
life_exp.isna().sum() / life_exp.shape[0]

index                            0.000000
GhoCode                          0.000000
GhoDisplay                       0.000000
PublishStateCode                 0.000000
PublishStateDisplay              0.000000
YearCode                         0.000000
YearDisplay                      0.000000
RegionCode                       0.000000
RegionDisplay                    0.000000
WorldBankIncomeGroupGroupCode    0.181648
WorldBankIncomeGroupDisplay      0.181648
CountryCode                      0.000000
CountryDisplay                   0.000000
SexCode                          0.000000
SexDisplay                       0.000000
DisplayValue                     0.000000
Numeric                          0.000000
dtype: float64

In [172]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –ø–æ –≥–æ–¥–∞–º –≤ —Ç–∞–±–ª–∏—Ü–µ lifeexpectancy-verbose.csv
life_exp['WorldBankIncomeGroupGroupCode'].isna().groupby(life_exp['YearDisplay']).sum()

YearDisplay
1990       0
2000       0
2012       0
2013    1164
Name: WorldBankIncomeGroupGroupCode, dtype: int64

–¢–æ –µ—Å—Ç—å —É –Ω–∞—Å –Ω–µ—Ç –¥–∞–Ω–Ω—ã—Ö –ø–æ 1164 —Å—Ç—Ä–∞–Ω–∞–º –∑–∞ 2013 –≥–æ–¥, –ø–æ–ø—Ä–æ–±—É–µ–º –Ω–∞–π—Ç–∏ –¥–∞—Ç–∞—Å–µ—Ç—ã –Ω–∞ —Å—Ç–æ—Ä–æ–Ω–Ω–∏—Ö –∏—Å—Ç–æ—á–Ω–∏–∫–∞—Ö. –ù–∞—à–ª–∏ –¥–∞–Ω–Ω—ã–µ –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞ (–≤ –Ω–∞—à–µ–º –∏–∑–Ω–∞—á–∞–ª—å–Ω–æ–º –¥–∞—Ç–∞—Å–µ—Ç–µ - –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è —Ç–æ–∂–µ –∏–∑ –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞ https://ourworldindata.org/grapher/world-bank-income-groups?tab=table&time=2013&overlay=download-data) –ö–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è –∏–¥–µ–Ω—Ç–∏—á–Ω–∞: Low income -> Lower middle income -> Upper middle income -> High income, –ø—ç—Ç–æ–º—É –º–æ–∂–µ–º —Å–¥–µ–ª–∞—Ç—å –∑–∞–º–µ–Ω—É

–ú–µ—Ä–∂–∏–º –ø–æ –∫–æ–¥—É —Å—Ç—Ä–∞–Ω—ã (—Ç–∞–∫ –∫–∞–∫ –Ω–∞–∑–≤–∞–Ω–∏—è –º–æ–≥—É—Ç –æ—Ç–ª–∏—á–∞—Ç—å—Å—è –ø–æ –Ω–∞–ø–∏—Å–∞–Ω–∏—é), —Ç–∞–∫–∂–µ –ø—Ä–∏–≤–æ–¥–∏–º –ø—É—Ç–µ–º –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–π, —Å–ª–æ–≤–∞—Ä–µ–π –∏ –º–µ—Ç–æ–¥–∞ map() –∫ –µ–¥–∏–Ω—ã–º –∑–Ω–∞—á–µ–Ω–∏—è–º, —Å—É—â–µ—Å—Ç–≤–æ–≤–∞–≤—à–∏–º –≤ –Ω–∞—à–µ–º –¥–∞—Ç–∞—Å–µ—Ç–µ

In [173]:
ext_src = pd.read_csv('external_source.csv')
life_exp = pd.read_csv('lifeexpectancy-verbose.csv')
dict_display = {'WB_HI':'High_income',
             'WB_LMI':'Lower_middle_income',
             'WB_UMI':'Upper_middle_income',
             'WB_LI':'Low_income'}

dict_code = {'High-income countries':'WB_HI',
             'Lower-middle-income countries':'WB_LMI',
             'Upper-middle-income countries':'WB_UMI',
             'Low-income countries':'WB_LI'}

In [174]:
ext_src.columns = ['CountryDisplay', 'CountryCode', 'YearCode', 'WorldBankIncomeGroupGroupCode']

ext_src = ext_src[ext_src['YearCode'] == 2013]
ext_src['WorldBankIncomeGroupGroupCode'] = ext_src['WorldBankIncomeGroupGroupCode'].map(dict_code)


life_exp = life_exp.merge(
    ext_src[['CountryCode', 'WorldBankIncomeGroupGroupCode']],
    on='CountryCode',
    how='left',
    suffixes=('', '_new')
)

life_exp

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric,WorldBankIncomeGroupGroupCode_new
0,0,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000,WB_LMI
1,1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000,WB_HI
2,2,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000,WB_LMI
3,3,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000,WB_LMI
4,4,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000,WB_UMI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,6403,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000,WB_LMI
6404,6404,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000,WB_UMI
6405,6405,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000,WB_LI
6406,6406,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000,WB_UMI
6407,6407,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2013,2013,EUR,Europe,NaN,NaN,ARM,Armenia,BTSX,Both sexes,71,71.02699,WB_LMI

–°–º–µ—Ä–∂–∏–ª–∏, –Ω–æ –Ω–∞–¥–æ –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ —É–¥–∞–ª–∏—Ç—å –∫–æ–ª–æ–Ω–∫—É WorldBankIncomeGroupGroupCode_new, –∫–æ—Ç–æ—Ä—É—é —Å–æ–∑–¥–∞–≤–∞–ª–∏ –¥–ª—è —É–¥–æ–±—Å—Ç–≤–∞

In [175]:
life_exp['WorldBankIncomeGroupGroupCode'] = life_exp['WorldBankIncomeGroupGroupCode'].fillna(life_exp['WorldBankIncomeGroupGroupCode_new'])
life_exp['WorldBankIncomeGroupDisplay'] = life_exp['WorldBankIncomeGroupDisplay'].fillna(life_exp['WorldBankIncomeGroupGroupCode_new'])
life_exp['WorldBankIncomeGroupDisplay'] = life_exp['WorldBankIncomeGroupGroupCode'].map(dict_display)
life_exp.drop(columns=['WorldBankIncomeGroupGroupCode_new'], inplace=True)

–£ –Ω–∞—Å –ø–æ–ª—É—á–∏–ª—Å—è –¥–æ–ø–æ–ª–Ω–µ–Ω–Ω—ã–π –¥–∞—Ç–∞—Å–µ—Ç:

In [176]:
life_exp

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,0,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,2,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,3,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,4,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,6403,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,6404,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,6405,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,6406,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,6407,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2013,2013,EUR,Europe,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

–ü—Ä–æ–≤–µ—Ä–∏–º —Å–∫–æ–ª—å–∫–æ —Ç–µ–ø–µ—Ä—å –ø—Ä–æ–ø—É—Å–∫–æ–≤:

In [177]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                    0
Americas                  0
Eastern Mediterranean     0
Europe                    0
South_East Asia           0
Western Pacific          18
Name: WorldBankIncomeGroupDisplay, dtype: int64

–ò—Ö —Å—Ç–∞–ª–æ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –º–∞–ª–æ, –≤—ã–≤–æ–¥–∏–º —Å—Ç—Ä–∞–Ω—ã, —É –∫–æ—Ç–æ—Ä—ã—Ö –æ—Ç—Å—É—Ç—Å—Ç–≤—É–µ—Ç –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏ –æ—Ç –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞ (WorldBankIncomeGroupDisplay –∏ WorldBankIncomeGroupGroupCode)

In [178]:
missing_income = life_exp[life_exp['WorldBankIncomeGroupDisplay'].isna()][['CountryDisplay', 'WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']]
missing_income.drop_duplicates()

    CountryDisplay WorldBankIncomeGroupDisplay WorldBankIncomeGroupGroupCode
19            Niue                         NaN                           NaN
98    Cook Islands                         NaN                           NaN
853          Nauru                         NaN                           NaN

–£ –Ω–∞—Å –æ—Å—Ç–∞–ª–æ—Å—å 3 —Å—Ç—Ä–∞–Ω—ã, –¥–ª—è –∫–æ—Ç–æ—Ä—ã—Ö –¥–∞–Ω–Ω—ã—Ö –ø–æ –¥–æ—Ö–æ–¥–∞–º –∑–∞ 2013 –≥–æ–¥ –Ω–µ—Ç. –í–æ –≤–Ω–µ—à–Ω–µ–º –¥–∞—Ç–∞—Å–µ—Ç–µ external_source.csv –¥–ª—è —Å—Ç—Ä–∞–Ω—ã Nauru –¥–∞–Ω–Ω—ã–µ –µ—Å—Ç—å —Ç–æ–ª—å–∫–æ —Å 2015 –≥–æ–¥–∞, –¥–ª—è Cook Islands –∏ Niue –¥–∞–Ω–Ω—ã—Ö –≤–æ–≤—Å–µ –Ω–µ—Ç.

–ò–∑—É—á–∏–≤, –∫–∞–∫ –≤—ã—á–∏—Å–ª—è–µ—Ç—Å—è –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞ –¥–ª—è —Å—Ç—Ä–∞–Ω, –Ω–∞—à–ª–∏ —á—Ç–æ –æ–Ω–∞ –∑–∞–≤–∏—Å–∏—Ç –æ—Ç –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è "gross national income (GNI) per capita". –ö–∞–∂–¥—ã–π —Ñ–∏–Ω–∞–Ω—Å–æ–≤—ã–π –≥–æ–¥ (FY) –≥—Ä–∞–Ω–∏—Ü—ã Low income -> Lower middle income -> Upper middle income -> High income –ø–µ—Ä–µ—Å–º–∞—Ç—Ä–∏–≤–∞—é—Ç—Å—è  —Å —É—á—ë—Ç–æ–º –∏–Ω—Ñ–ª—è—Ü–∏–∏ –∏ –æ–±–º–µ–Ω–Ω–æ–≥–æ –∫—É—Ä—Å–∞ –¥–æ–ª–ª–∞—Ä–∞ –°–®–ê. –ù–∞ –≤—Ä–µ–º—è 2013 –≥–æ–¥–∞ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏ –±—ã–ª–∏ —Ç–∞–∫–∏–µ:

–ù–∏–∑–∫–∏–π –¥–æ—Ö–æ–¥ (Low income): $1,035 –∏–ª–∏ –º–µ–Ω—å—à–µ

–ù–∏–∂–Ω–∏–π —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥ (Lower middle income): –æ—Ç $1,036 –¥–æ $4,085

–í–µ—Ä—Ö–Ω–∏–π —Å—Ä–µ–¥–Ω–∏–π –¥–æ—Ö–æ–¥ (Upper middle income): –æ—Ç $4,086 –¥–æ $12,615

–í—ã—Å–æ–∫–∏–π –¥–æ—Ö–æ–¥ (High income): $12,616 –∏–ª–∏ –±–æ–ª—å—à–µ

(–ò—Å—Ç–æ—á–Ω–∏–∫ https://www.childrenpalliativecarecongress.org/congress-2014/wp-content/uploads/2013/09/World-Bank-List-of-Economies-2013.pdf, –ø–æ—Å–ª–µ–¥–Ω—è—è —Å—Ç—Ä–∞–Ω–∏—Ü–∞)

–î–ª—è Nauru GNI per capita —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç 11 340 –¥–æ–ª–ª–∞—Ä–æ–≤ –°–®–ê —Å–æ–≥–ª–∞—Å–Ω–æ https://www.macrotrends.net/global-metrics/countries/nru/nauru/gni-per-capita, –µ–≥–æ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è - Upper middle income

–î–ª—è Cook Islands GNI per capita —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç 16,217.2 –¥–æ–ª–ª–∞—Ä–æ–≤ –°–®–ê —Å–æ–≥–ª–∞—Å–Ω–æ https://ivanstat.com/en/gni/ck.html, –µ–≥–æ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è - High income

–î–ª—è Niue GNI per capita —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç  –¥–æ–ª–ª–∞—Ä–æ–≤ –°–®–ê —Å–æ–≥–ª–∞—Å–Ω–æ , –µ–≥–æ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏—è - Upper middle income

In [179]:
life_exp.loc[life_exp['CountryDisplay'] == 'Nauru', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['Upper_middle_income', 'WB_UMI']
life_exp.loc[life_exp['CountryDisplay'] == 'Cook Islands', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['High_income', 'WB_HI']
# –æ—Ñ–∏—Ü–∏–∞–ª—å–Ω—ã—Ö –¥–∞–Ω–Ω—ã—Ö GNI per capita –∑–∞ 2013 –≥–æ–¥ –Ω–µ—Ç.
# –ù–∏—É—ç –∏—Å–ø–æ–ª—å–∑—É–µ—Ç –Ω–æ–≤–æ–∑–µ–ª–∞–Ω–¥—Å–∫–∏–π –¥–æ–ª–ª–∞—Ä, –ø–æ–ª—É—á–∞–µ—Ç —Ñ–∏–Ω–∞–Ω—Å–æ–≤—É—é –ø–æ–¥–¥–µ—Ä–∂–∫—É –æ—Ç –ù–æ–≤–æ–π –ó–µ–ª–∞–Ω–¥–∏–∏ –∏ –∏–º–µ–µ—Ç —Å—Ö–æ–∂–∏–π —É—Ä–æ–≤–µ–Ω—å –∂–∏–∑–Ω–∏ —Å –¥—Ä—É–≥–∏–º–∏ –≤—ã—Å–æ–∫–æ–¥–æ—Ö–æ–¥–Ω—ã–º–∏ —Ç–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–∏–º–∏ —Ç–µ—Ä—Ä–∏—Ç–æ—Ä–∏—è–º–∏.
# –ü–æ—ç—Ç–æ–º—É —Å—Ç—Ä–∞–Ω—É —Ä–∞–∑—É–º–Ω–æ –æ—Ç–Ω–µ—Å—Ç–∏ –∫ –∫–∞—Ç–µ–≥–æ—Ä–∏–∏ High income –ø–æ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏–∏ –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞.
life_exp.loc[life_exp['CountryDisplay'] == 'Niue', ['WorldBankIncomeGroupDisplay', 'WorldBankIncomeGroupGroupCode']] = ['High_income', 'WB_HI']

In [180]:
life_exp['WorldBankIncomeGroupDisplay'].isna().groupby(life_exp['RegionDisplay']).sum()

RegionDisplay
Africa                   0
Americas                 0
Eastern Mediterranean    0
Europe                   0
South_East Asia          0
Western Pacific          0
Name: WorldBankIncomeGroupDisplay, dtype: int64

–ü—Ä–æ–ø—É—Å–∫–æ–≤ –±–æ–ª—å—à–µ –Ω–µ –æ—Å—Ç–∞–ª–æ—Å—å:) –°–æ—Ö—Ä–∞–Ω—è–µ–º —Ç–∞–±–ª–∏—Ü—É –≤ –Ω–∞—à–µ–º –æ–∫—Ä—É–∂–µ–Ω–∏–∏

In [181]:
life_exp.to_csv('life_expectancy_full.csv')

### 9

–í—Å–µ –ª–∏ –ø—Ä–∏–∑–Ω–∞–∫–∏ –Ω–µ—Å—É—Ç –≤ —Å–µ–±–µ –ø–æ–ª–µ–∑–Ω—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é? –ü–æ—á–µ–º—É –≤—ã —Ç–∞–∫ —Å—á–∏—Ç–∞–µ—Ç–µ? –ò–∑–±–∞–≤—å—Ç–µ—Å—å –æ—Ç –Ω–µ–Ω—É–∂–Ω—ã—Ö —Å—Ç–æ–ª–±—Ü–æ–≤. –°–≤–æ–π –≤—ã–±–æ—Ä –∞—Ä–≥—É–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ

*–ü—Ä–∏–º–µ—á–∞–Ω–∏–µ. –ù–µ –∑–∞–±—É–¥—å—Ç–µ —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –≤—Å–µ –∏–∑–º–µ–Ω–µ–Ω–∏—è! –í –ø–æ—Å–ª–µ–¥—É—é—â–∏—Ö –∑–∞–¥–∞–Ω–∏—è—Ö –≤—ã –¥–æ–ª–∂–Ω—ã —Ä–∞–±–æ—Ç–∞—Ç—å —Å —É–∂–µ –æ–±–Ω–æ–≤–ª–µ–Ω–Ω—ã–º–∏ –¥–∞—Ç–∞—Å–µ—Ç–∞–º–∏.*

In [182]:
#—Å–ø–∏—Å–æ–∫ –ø—Ä–∏–∑–Ω–∞–∫–æ–≤
life_exp.columns

Index(['index', 'GhoCode', 'GhoDisplay', 'PublishStateCode',
       'PublishStateDisplay', 'YearCode', 'YearDisplay', 'RegionCode',
       'RegionDisplay', 'WorldBankIncomeGroupGroupCode',
       'WorldBankIncomeGroupDisplay', 'CountryCode', 'CountryDisplay',
       'SexCode', 'SexDisplay', 'DisplayValue', 'Numeric'],
      dtype='object')

–ö–æ–ª–æ–Ω–∫–∞ index –Ω–µ –Ω–µ—Å–µ—Ç –Ω–∏–∫–∞–∫–æ–≥–æ –ø–æ–ª–µ–∑–Ω–æ–≥–æ –∑–Ω–∞—á–µ–Ω–∏—è, –≤—Å–µ–≥–æ –ª–∏—à—å —É–Ω–∏–∫–∞–ª—å–Ω—ã–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä (—Å—á–∏—Ç–∞—é —á—Ç–æ –≤ —Ñ–∏–ª—å–º–∞—Ö –æ–Ω –±—ã–ª –±—ã –ø–æ–ª–µ–∑–µ–Ω, –Ω–æ —Ç—É—Ç - –Ω–µ—Ç). –ù–µ –¥–∞–µ—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ –∑–∞–ø–∏—Å–∏

In [183]:
# —É–¥–∞–ª—è–µ–º index
life_exp.drop(columns=['index'], inplace=True)
life_exp

,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2013,2013,EUR,Europe,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

–û —Ç–∏–ø–∞—Ö –æ—Ç—á–µ—Ç–æ–≤: —Ü–µ–ª–µ—Å–æ–æ–±—Ä–∞–∑–Ω–æ –æ—Å—Ç–∞–≤–∏—Ç—å —Ç–æ–ª—å–∫–æ –∫–æ–¥—ã, –∞ –∏—Ö —Ç–µ–∫—Å—Ç–æ–≤—ã–µ –æ–ø–∏—Å–∞–Ω–∏—è –≤—ã–Ω–µ—Å—Ç–∏ –≤ –æ—Ç–¥–µ–ª—å–Ω—ã–π —Å–ª–æ–≤–∞—Ä—å. –¢–∞–∫–æ–π –ø–æ–¥—Ö–æ–¥ —É–ø—Ä–æ—â–∞–µ—Ç –æ–±—Ä–∞–±–æ—Ç–∫—É –¥–∞–Ω–Ω—ã—Ö –∏ –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏, –∏—Å–∫–ª—é—á–∞–µ—Ç –æ—à–∏–±–∫–∏ –∏–∑-–∑–∞ —Ä–∞–∑–Ω—ã—Ö –≤–∞—Ä–∏–∞–Ω—Ç–æ–≤ –Ω–∞–ø–∏—Å–∞–Ω–∏—è —Ç–µ–∫—Å—Ç–∞ –∏ –ø—Ä–∏ —ç—Ç–æ–º —Å–æ—Ö—Ä–∞–Ω—è–µ—Ç –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –ø—Ä–∏ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ—Å—Ç–∏ –ø–æ–ª—É—á–∏—Ç—å —á–µ–ª–æ–≤–µ–∫–æ-—á–∏—Ç–∞–µ–º–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —á–µ—Ä–µ–∑ —Å–ª–æ–≤–∞—Ä—å.

In [184]:
# —Å–æ–∑–¥–∞–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–æ–≥–æ —Å–ª–æ–≤–∞—Ä—è
gho_dict = dict(life_exp[['GhoCode', 'GhoDisplay']].drop_duplicates().values)

# —É–¥–∞–ª–µ–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∞ GhoDisplay
life_exp.drop(columns=['GhoDisplay'], inplace=True)
life_exp

,GhoCode,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,PUBLISHED,Published,2013,2013,EUR,Europe,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

In [185]:
gho_dict

{'WHOSIS_000001': 'Life expectancy at birth (years)',
 'WHOSIS_000002': 'Healthy life expectancy (HALE) at birth (years)',
 'WHOSIS_000015': 'Life expectancy at age 60 (years)'}

–£ –∫–æ–ª–æ–Ω–æ–∫ PublishStateCode –∏ PublishStateDisplay –Ω—É–ª–µ–≤–∞—è –ø–æ–ª–µ–∑–Ω–æ—Å—Ç—å, —Ç–∞–∫ –∫–∞–∫ –≤—Å–µ —Å—Ç—Ä–æ–∫–∏ –∏–º–µ—é—Ç –∑–Ω–∞—á–µ–Ω–∏–µ Published

In [186]:
life_exp['PublishStateCode'].unique()

array(['PUBLISHED'], dtype=object)

In [187]:
life_exp['PublishStateDisplay'].unique()

array(['Published'], dtype=object)

–í –∫–æ–Ω—Ç–µ–∫—Å—Ç–µ –Ω–∞—à–µ–π –∑–∞–¥–∞—á–∏ —ç—Ç–∏ –ø—Ä–∏–∑–Ω–∞–∫–∏ –Ω–µ –≤–ª–∏—è—é—Ç –Ω–∞ –∞–Ω–∞–ª–∏–∑, –ø–æ—ç—Ç–æ–º—É —É–¥–∞–ª—è–µ–º

In [188]:
# —É–¥–∞–ª–µ–Ω–∏–µ PublishStateCode –∏ PublishStateDisplay
life_exp.drop(columns=['PublishStateCode', 'PublishStateDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,2013,2013,EUR,Europe,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

–ò–º–µ–µ—Ç—Å—è 2 –∫–æ–ª–æ–Ω–∫–∏, –æ–±–æ–∑–Ω–∞—á–∞—é—â–∏–µ –≥–æ–¥. –ú–æ–∂–Ω–æ —É–¥–∞–ª–∏—Ç—å –æ–¥–Ω—É, —Ç–∞–∫ –∫–∞–∫ –æ–Ω–∏ –∏–¥–µ–Ω—Ç–∏—á–Ω—ã –ø–æ –∑–Ω–∞—á–µ–Ω–∏—è–º. –ì–æ–¥ –∫—Ä–∏—Ç–∏—á–µ—Å–∫–∏ –≤–∞–∂–µ–Ω –¥–ª—è –¥–∞–ª—å–Ω–µ–π—à–µ–≥–æ –∞–Ω–∞–ª–∏–∑–∞ —Ç—Ä–µ–Ω–¥–æ–≤

In [189]:
life_exp['YearCode'].unique()

array([1990, 2012, 2000, 2013])

In [190]:
life_exp['YearDisplay'].unique()

array([1990, 2012, 2000, 2013])

In [191]:
# —É–¥–∞–ª—è–µ–º –∫–æ–ª–æ–Ω–∫—É YearDisplay
life_exp.drop(columns=['YearDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,2013,EUR,Europe,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

–ü–æ–¥—Ö–æ–¥ –∫ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏–∏ —Ä–µ–≥–∏–æ–Ω–æ–≤ —Å—Ö–æ–∂ —Å –æ–±—Ä–∞–±–æ—Ç–∫–æ–π —Ç–∏–ø–æ–≤ —Å—Ç–∞—Ç–µ–π, —Ç–∞–∫–∂–µ —Å–æ–∑–¥–∞–µ–º —Å–ø—Ä–∞–≤–æ—á–Ω—ã–π —Å–ª–æ–≤–∞—Ä—å, –∫–æ—Ç–æ—Ä—ã–º –º–æ–∂–µ–º –ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –≤ –±—É–¥—É—â–µ–º. –£–¥–∞–ª—è–µ–º —Ç–µ–∫—Å—Ç–æ–≤—É—é —Ä–∞—Å—à–∏—Ñ—Ä–æ–≤–∫—É, —Ç–∞–∫ –∫–∞–∫ –∫–æ–¥ —Ä–µ–≥–∏–æ–Ω–∞ —á–∏—Ç–∞–µ—Ç—Å—è –∫–æ–º–ø—å—é—Ç–µ—Ä–æ–º –ª—É—á—à–µ

In [192]:
# —Å–æ–∑–¥–∞–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–æ–≥–æ —Å–ª–æ–≤–∞—Ä—è
region_dict = dict(life_exp[['RegionCode', 'RegionDisplay']].drop_duplicates().values)

# —É–¥–∞–ª–µ–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∞ RegionDisplay
life_exp.drop(columns=['RegionDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,1990,AMR,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,2012,EUR,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,2000,EMR,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,2000,AFR,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,1990,SEAR,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,1990,WPR,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,1990,AFR,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,2012,EUR,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,2013,EUR,WB_LMI,Lower_middle_income,ARM,Armenia,BTSX,Both sexes,71,71.02699

In [193]:
region_dict

{'AMR': 'Americas',
 'EUR': 'Europe',
 'EMR': 'Eastern Mediterranean',
 'AFR': 'Africa',
 'SEAR': 'South_East Asia',
 'WPR': 'Western Pacific'}

–°—Ö–æ–∂–∞—è —Å–∏—Ç—É–∞—Ü–∏—è –∏ —Å –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏–µ–π –¥–æ—Ö–æ–¥–æ–≤ –æ—Ç –í—Å–µ–º–∏—Ä–Ω–æ–≥–æ –±–∞–Ω–∫–∞. –ê–Ω–∞–ª–æ–≥–∏—á–Ω–æ –æ—Å—Ç–∞–≤–ª—è–µ–º –∫–æ–¥—ã, –¥–ª—è —É–ø—Ä–æ—â–µ–Ω–∏—è —á—Ç–µ–Ω–∏—è –∫–æ–º–ø—å—é—Ç–µ—Ä–æ–º. –°–æ–∑–¥–∞–µ–º —Å–ø—Ä–∞–≤–æ—á–Ω—ã–π —Å–ª–æ–≤–∞—Ä—å –¥–ª—è –ø—Ä–∏–¥–∞–Ω–∏—è –∑–Ω–∞—á–µ–Ω–∏—è–º —á–µ–ª–æ–≤–µ–∫–æ—á–∏—Ç–∞–µ–º–æ–≥–æ –≤–∏–¥–∞

In [194]:
# —Å–æ–∑–¥–∞–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–æ–≥–æ —Å–ª–æ–≤–∞—Ä—è
income_dict = dict(life_exp[['WorldBankIncomeGroupGroupCode', 'WorldBankIncomeGroupDisplay']].drop_duplicates().values)

# —É–¥–∞–ª–µ–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∞ WorldBankIncomeGroupDisplay
life_exp.drop(columns=['WorldBankIncomeGroupDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,Nicaragua,MLE,Male,68,68.00000
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,Ireland,MLE,Male,69,69.30000
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,Yemen,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,Nigeria,FMLE,Female,48,48.00000
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,Thailand,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,Albania,MLE,Male,64,63.50000
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,Armenia,BTSX,Both sexes,71,71.02699

In [195]:
income_dict

{'WB_LMI': 'Lower_middle_income',
 'WB_HI': 'High_income',
 'WB_LI': 'Low_income',
 'WB_UMI': 'Upper_middle_income'}

–°–∏—Ç—É–∞—Ü–∏—è –Ω–µ –º–µ–Ω—è–µ—Ç—Å—è –∏ —Å–æ —Å—Ç—Ä–∞–Ω–æ–π –∏ –ø–æ–ª–æ–º, —Å–æ–∑–¥–∞–µ–º —Å–æ–æ—Ç–≤–µ—Ç—Å–≤—É—é—â–∏–µ —Å–ª–æ–≤–∞—Ä–∏

In [196]:
# —Å–æ–∑–¥–∞–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–æ–≥–æ —Å–ª–æ–≤–∞—Ä—è
country_dict = dict(life_exp[['CountryCode', 'CountryDisplay']].drop_duplicates().values)

# —É–¥–∞–ª–µ–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∞ WorldBankIncomeGroupDisplay
life_exp.drop(columns=['CountryDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,SexDisplay,DisplayValue,Numeric
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,Male,68,68.00000
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,Male,69,69.30000
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,Both sexes,61,61.00000
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,Female,48,48.00000
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,Female,19,19.00000
...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,Both sexes,68,68.00000
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,Both sexes,16,16.00000
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,Female,51,51.00000
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,Male,64,63.50000
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,Both sexes,71,71.02699

In [197]:
country_dict

{'NIC': 'Nicaragua',
 'IRL': 'Ireland',
 'YEM': 'Yemen',
 'NGA': 'Nigeria',
 'THA': 'Thailand',
 'CHL': 'Chile',
 'ZWE': 'Zimbabwe',
 'DEU': 'Germany',
 'ESP': 'Spain',
 'BWA': 'Botswana',
 'PAK': 'Pakistan',
 'NIU': 'Niue',
 'WSM': 'Samoa',
 'JPN': 'Japan',
 'MNG': 'Mongolia',
 'BLZ': 'Belize',
 'MEX': 'Mexico',
 'BRA': 'Brazil',
 'AUS': 'Australia',
 'RWA': 'Rwanda',
 'BOL': 'Bolivia (Plurinational State of)',
 'AND': 'Andorra',
 'LCA': 'Saint Lucia',
 'DJI': 'Djibouti',
 'BTN': 'Bhutan',
 'TON': 'Tonga',
 'BGR': 'Bulgaria',
 'SYR': 'Syrian Arab Republic',
 'MMR': 'Myanmar',
 'BRB': 'Barbados',
 'KWT': 'Kuwait',
 'GRD': 'Grenada',
 'SUR': 'Suriname',
 'POL': 'Poland',
 'NER': 'Niger',
 'ARM': 'Armenia',
 'STP': 'Sao Tome and Principe',
 'GIN': 'Guinea',
 'PAN': 'Panama',
 'KOR': 'Republic of Korea',
 'CZE': 'Czech Republic',
 'SLB': 'Solomon Islands',
 'ISL': 'Iceland',
 'KEN': 'Kenya',
 'IND': 'India',
 'GTM': 'Guatemala',
 'BLR': 'Belarus',
 'VUT': 'Vanuatu',
 'MYS': 'Malaysia',
 'ATG': 'Antigua and Barbuda',
 'NLD': 'Netherlands',
 'UGA': 'Uganda',
 'FJI': 'Fiji',
 'BEN': 'Benin',
 'EGY': 'Egypt',
 'VCT': 'Saint Vincent and the Grenadines',
 'SEN': 'Senegal',
 'LTU': 'Lithuania',
 'GUY': 'Guyana',
 'URY': 'Uruguay',
 'UKR': 'Ukraine',
 'CHN': 'China',
 'FRA': 'France',
 'COM': 'Comoros',
 'PRY': 'Paraguay',
 'MDV': 'Maldives',
 'PHL': 'Philippines',
 'GHA': 'Ghana',
 'SWZ': 'Swaziland',
 'GNQ': 'Equatorial Guinea',
 'SWE': 'Sweden',
 'KNA': 'Saint Kitts and Nevis',
 'NRU': 'Nauru',
 'TZA': 'United Republic of Tanzania',
 'TJK': 'Tajikistan',
 'DOM': 'Dominican Republic',
 'SDN': 'Sudan',
 'ZMB': 'Zambia',
 'AZE': 'Azerbaijan',
 'COL': 'Colombia',
 'MKD': 'The former Yugoslav republic of Macedonia',
 'MUS': 'Mauritius',
 'DZA': 'Algeria',
 'TUR': 'Turkey',
 'COK': 'Cook Islands',
 'LKA': 'Sri Lanka',
 'RUS': 'Russian Federation',
 'DMA': 'Dominica',
 'HRV': 'Croatia',
 'SSD': 'South Sudan',
 'PLW': 'Palau',
 'FSM': 'Micronesia (Federated States of)',
 'HTI': 'Haiti',
 'SVK': 'Slovakia',
 'BRN': 'Brunei Darussalam',
 'COG': 'Congo',
 'AUT': 'Austria',
 'GBR': 'United Kingdom of Great Britain and Northern Ireland',
 'SMR': 'San Marino',
 'CUB': 'Cuba',
 'BHR': 'Bahrain',
 'TGO': 'Togo',
 'CIV': "C√¥te d'Ivoire",
 'USA': 'United States of America',
 'PRK': "Democratic People's Republic of Korea",
 'VNM': 'Viet Nam',
 'CPV': 'Cabo Verde',
 'ETH': 'Ethiopia',
 'COD': 'Democratic Republic of the Congo',
 'MDA': 'Republic of Moldova',
 'MNE': 'Montenegro',
 'LBR': 'Liberia',
 'HUN': 'Hungary',
 'IRQ': 'Iraq',
 'ZAF': 'South Africa',
 'MDG': 'Madagascar',
 'GRC': 'Greece',
 'JOR': 'Jordan',
 'ARG': 'Argentina',
 'SGP': 'Singapore',
 'MRT': 'Mauritania',
 'SAU': 'Saudi Arabia',
 'LBY': 'Libya',
 'IRN': 'Iran (Islamic Republic of)',
 'TUN': 'Tunisia',
 'CMR': 'Cameroon',
 'MLI': 'Mali',
 'BHS': 'Bahamas',
 'BIH': 'Bosnia and Herzegovina',
 'GEO': 'Georgia',
 'CRI': 'Costa Rica',
 'CAN': 'Canada',
 'SLE': 'Sierra Leone',
 'TLS': 'Timor_Leste',
 'TUV': 'Tuvalu',
 'NOR': 'Norway',
 'ARE': 'United Arab Emirates',
 'MLT': 'Malta',
 'PRT': 'Portugal',
 'CHE': 'Switzerland',
 'GAB': 'Gabon',
 'SRB': 'Serbia',
 'NPL': 'Nepal',
 'CAF': 'Central African Republic',
 'MWI': 'Malawi',
 'PNG': 'Papua New Guinea',
 'TKM': 'Turkmenistan',
 'GMB': 'Gambia',
 'ERI': 'Eritrea',
 'BDI': 'Burundi',
 'KHM': 'Cambodia',
 'NZL': 'New Zealand',
 'KAZ': 'Kazakhstan',
 'BFA': 'Burkina Faso',
 'KIR': 'Kiribati',
 'ECU': 'Ecuador',
 'NAM': 'Namibia',
 'OMN': 'Oman',
 'LSO': 'Lesotho',
 'FIN': 'Finland',
 'BGD': 'Bangladesh',
 'IDN': 'Indonesia',
 'VEN': 'Venezuela (Bolivarian Republic of)',
 'ROU': 'Romania',
 'UZB': 'Uzbekistan',
 'LAO': "Lao People's Democratic Republic",
 'SOM': 'Somalia',
 'PER': 'Peru',
 'SVN': 'Slovenia',
 'SYC': 'Seychelles',
 'CYP': 'Cyprus',
 'AGO': 'Angola',
 'LVA': 'Latvia',
 'EST': 'Estonia',
 'LUX': 'Luxembourg',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'SLV': 'El Salvador',
 'DNK': 'Denmark',
 'MCO': 'Monaco',
 'AFG': 'Afghanistan',
 'QAT': 'Qatar',
 'TTO': 'Trinidad and Tobago',
 'GNB': 'Guinea_Bissau',
 'JAM': 'Jamaica',
 'MOZ': 'Mozambique',
 'MHL': 'Marshall Islands',
 'KGZ': 'Kyrgyzstan',
 'LBN': 'Lebanon',
 'HND': 'Honduras',
 'MAR': 'Morocco',
 'ALB': 'Albania',
 'TCD': 'Chad',
 'BEL': 'Belgium'}

In [198]:
# —Å–æ–∑–¥–∞–Ω–∏–µ —Å–ø—Ä–∞–≤–æ—á–Ω–æ–≥–æ —Å–ª–æ–≤–∞—Ä—è
sex_dict = dict(life_exp[['SexCode', 'SexDisplay']].drop_duplicates().values)

# —É–¥–∞–ª–µ–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∞ WorldBankIncomeGroupDisplay
life_exp.drop(columns=['SexDisplay'], inplace=True)
life_exp

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,DisplayValue,Numeric
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,68,68.00000
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,69,69.30000
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,61,61.00000
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,48,48.00000
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,19,19.00000
...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,68,68.00000
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,16,16.00000
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,51,51.00000
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,64,63.50000
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,71,71.02699

In [199]:
sex_dict

{'MLE': 'Male', 'BTSX': 'Both sexes', 'FMLE': 'Female'}

–ö–æ–ª–æ–Ω–∫–∏ DisplayValue –∏ Numeric –Ω–µ —É–¥–∞–ª—è–µ–º, —Ç–∞–∫ –∫–∞–∫ –æ–Ω–∏ –≤–ø–µ—Ä–≤—É—é –æ—á–µ—Ä–µ–¥—å –≤–∞–∂–Ω—ã –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞. –≠—Ç–æ –æ—Å–Ω–æ–≤–Ω–∞—è —á–∏—Å–ª–æ–≤–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è, –Ω–∞ –∫–æ—Ç–æ—Ä–æ–π —Å—Ç—Ä–æ—è—Ç—Å—è –≤—Å–µ —Ä–∞—Å—á—ë—Ç—ã, –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏, –∫–æ—Ä—Ä–µ–ª—è—Ü–∏–∏ –∏ –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏–∏. –£–¥–∞–ª–µ–Ω–∏–µ —ç—Ç–∏—Ö —Å—Ç–æ–ª–±—Ü–æ–≤ –ª–∏—à–∏—Ç –Ω–∞—Å –¥–∞–Ω–Ω—ã—Ö –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞.

In [200]:
# —Å–æ—Ö—Ä–∞–Ω—è–µ–º –¥–∞—Ç–∞—Å–µ—Ç
life_exp.to_csv('life_expectancy_after_task_9.csv')

### 10

–ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, –Ω–∞—Å–∫–æ–ª—å–∫–æ —Å–∏–ª—å–Ω–æ –∫–æ—Ä—Ä–µ–ª–∏—Ä—É—é—Ç –¥—Ä—É–≥ —Å –¥—Ä—É–≥–æ–º –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è —Ä–∞–∑–Ω—ã—Ö –≤–∏–¥–æ–≤ –∞–ª–∫–æ–≥–æ–ª—è (`beer_servings`,	`spirit_servings` –∏	`wine_servings`). –°–æ–∑–¥–∞–π—Ç–µ –¥–∞—Ç–∞—Ñ—Ä–µ–π–º —Å –ø–æ–ø–∞—Ä–Ω—ã–º–∏ –∫–æ—Ä—Ä–µ–ª—è—Ü–∏—è–º–∏ —ç—Ç–∏—Ö —Å—Ç–æ–ª–±—Ü–æ–≤ –¥—Ä—É–≥ —Å –¥—Ä—É–≥–æ–º. –ö–∞–∫–∏–µ –≤—ã–≤–æ–¥—ã –º–æ–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å?

In [201]:
alcohol_cols = ['beer_servings', 'spirit_servings', 'wine_servings']
drinks[alcohol_cols].corr()

                 beer_servings  spirit_servings  wine_servings
beer_servings         1.000000         0.458819       0.527172
spirit_servings       0.458819         1.000000       0.194797
wine_servings         0.527172         0.194797       1.000000

–ö–æ—Ä—Ä–µ–ª—è—Ü–∏–∏ —Ä–∞—Å—Å—á–∏—Ç–∞–Ω—ã –ø–æ —Å—Ä–µ–¥–Ω–µ–º—É –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—é –∞–ª–∫–æ–≥–æ–ª—è –Ω–∞ —á–µ–ª–æ–≤–µ–∫–∞ –≤ —Ä–∞–∑–Ω—ã—Ö —Å—Ç—Ä–∞–Ω–∞—Ö

beer_servings –∏ wine_servings –∏–º–µ—é—Ç —É–º–µ—Ä–µ–Ω–Ω—É—é –ø–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω—É—é —Å–≤—è–∑—å (‚âà0.53)

beer_servings –∏ spirit_servings —Ç–æ–∂–µ –ø–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω–æ —Å–≤—è–∑–∞–Ω—ã, –Ω–æ —Å–ª–∞–±–µ–µ (‚âà0.46)

spirit_servings –∏ wine_servings –ø–æ—á—Ç–∏ –Ω–µ –∫–æ—Ä—Ä–µ–ª–∏—Ä—É—é—Ç (‚âà0.19)

–≤—ã–≤–æ–¥: —Å—Ç—Ä–∞–Ω—ã, –≥–¥–µ –ª—é–¥–∏ –ø—å—é—Ç –±–æ–ª—å—à–µ –ø–∏–≤–∞, —á–∞—â–µ –ø—å—é—Ç –∏ –≤–∏–Ω–æ, –∞ —Å–ø–∏—Ä—Ç–Ω–æ–µ –Ω–µ —Ç–∞–∫ —Å–∏–ª—å–Ω–æ —Å–≤—è–∑–∞–Ω–æ —Å –¥—Ä—É–≥–∏–º–∏ –≤–∏–¥–∞–º–∏

dcs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html

### 11

–° –ø–æ–º–æ—â—å—é –¥–∞—Ç–∞—Å–µ—Ç–∞ –∏–∑ –∏–Ω—Ç–µ—Ä–Ω–µ—Ç–∞ (—Ñ–∞–π–ª iso.csv) –º—ã –º–µ—Ä–∂–∞ –∏—Ö –¥–æ–±–∞–≤–ª—è–µ–º –∫ –∫–∞–∂–¥–æ–π —Å—Ç—Ä–æ—á–∫–µ 3-—Ö –∑–Ω–∞—á–Ω—ã–π –∫–æ–¥ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏–∏ ISO, –≤ –¥–∞–ª—å–Ω–µ–π—à–µ–º —ç—Ç–∞ —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∏–∑–∞—Ü–∏—è –ø–æ–º–æ–∂–µ—Ç –Ω–∞–º –æ–±—ä–µ–¥–∏–Ω–∏—Ç—å –¥–∞—Ç–∞—Å–µ—Ç—ã

In [202]:
iso = pd.read_csv('iso.csv')

In [203]:
# –º–µ—Ä–∂–∏–º —Ç–∞–±–ª–∏—Ü—ã
drinks = drinks.merge(
    iso,
    left_on='country',
    right_on='country',
    how='left'
)

drinks = drinks.drop(columns=['Unnamed: 0'])

In [204]:
drinks

,index,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,CountryCode
0,0,Afghanistan,0,0,0,0.0,AFG
1,1,Albania,89,132,54,4.9,ALB
2,2,Algeria,25,0,14,0.7,DZA
3,3,Andorra,245,138,312,12.4,AND
4,4,Angola,217,57,45,5.9,AGO
...,...,...,...,...,...,...,...
188,188,Venezuela,333,100,3,7.7,VEN
189,189,Vietnam,111,2,1,2.0,VNM
190,190,Yemen,6,0,0,0.1,YEM
191,191,Zambia,32,19,4,2.5,ZMB
192,192,Zimbabwe,64,18,4,4.7,ZWE

In [205]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤
drinks.isna().sum()

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
CountryCode                     0
dtype: int64

In [206]:
# –æ–±—ä–µ–¥–∏–Ω—è–µ–º –ø–æ –∫–æ–¥—É —Å—Ç—Ä–∞–Ω—ã, –æ—Å—Ç–∞–≤–ª—è–µ–º –≤—Å–µ —Å—Ç—Ä–æ–∫–∏ –∏–∑ life_exp
merged_df = life_exp.merge(
    drinks.drop(columns=['index', 'country']),
    on='CountryCode',
    how='left',
    suffixes=('', '_drinks')
)

In [207]:
# –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤
merged_df.isna().sum()

GhoCode                           0
YearCode                          0
RegionCode                        0
WorldBankIncomeGroupGroupCode     0
CountryCode                       0
SexCode                           0
DisplayValue                      0
Numeric                           0
beer_servings                    39
spirit_servings                  39
wine_servings                    39
total_litres_of_pure_alcohol     39
dtype: int64

–ì–ª–∞–≤–Ω–æ–π —Ç–∞–±–ª–∏—Ü–µ–π —è–≤–ª—è–µ—Ç—Å—è life_exp —Å –¥–∞–Ω–Ω—ã–º–∏ –æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏, —Å–æ–ø—É—Ç—Å—Ç–≤—É—é—â–µ–π ‚Äî drinks —Å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–µ–π –æ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–∏ –∞–ª–∫–æ–≥–æ–ª—è. –¢–∞–±–ª–∏—Ü–∞ –æ –∂–∏–∑–Ω–∏ –±–æ–ª–µ–µ –¥–µ—Ç–∞–ª–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω–∞—è (–ø–æ –≥–æ–¥–∞–º, –ø–æ–ª—É, –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è–º), –∞ —Ç–∞–±–ª–∏—Ü–∞ –æ–± –∞–ª–∫–æ–≥–æ–ª–µ –∞–≥—Ä–µ–≥–∏—Ä–æ–≤–∞–Ω–∞ –Ω–∞ —É—Ä–æ–≤–Ω–µ —Å—Ç—Ä–∞–Ω—ã. –ú—ã —Ö–æ—Ç–∏–º –∏–∑—É—á–∏—Ç—å –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –æ—Ç –≤–Ω–µ—à–Ω–∏—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤, –≤ —á–∞—Å—Ç–Ω–æ—Å—Ç–∏ —É—Ä–æ–≤–Ω—è —É–ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è, –¥–æ—Ö–æ–¥–æ–≤ —Å—Ç—Ä–∞–Ω, —Ä–µ–≥–∏–æ–Ω–∞ –∏ –ø–æ–ª–∞. –ü–æ—ç—Ç–æ–º—É –∏—Å–ø–æ–ª—å–∑—É–µ–º –ª–µ–≤–æ–µ —Å–æ–µ–¥–∏–Ω–µ–Ω–∏–µ (left join) –ø–æ CountryCode: —Å–æ—Ö—Ä–∞–Ω—è–µ–º –≤—Å–µ —Å—Ç—Ä–æ–∫–∏ –∏–∑ –≥–ª–∞–≤–Ω–æ–π —Ç–∞–±–ª–∏—Ü—ã, –∞ –¥–∞–Ω–Ω—ã–µ –∏–∑ —Å–æ–ø—É—Ç—Å—Ç–≤—É—é—â–µ–π –ø–æ–¥—Ç—è–≥–∏–≤–∞–µ–º —Ç—É–¥–∞, –≥–¥–µ –æ–Ω–∏ –µ—Å—Ç—å. –ü–æ –æ–±—ä–µ–¥–∏–Ω–µ–Ω–∏—é —Ç–∞–±–ª–∏—Ü –Ω–µ –ø–æ–ª—É—á–∏–ª–æ—Å—å –∑–∞–¥–µ–π—Å—Ç–≤–æ–≤–∞—Ç—å –≤—Å–µ —Å—Ç—Ä–æ–∫–∏ –ø–æ –∞–ª–∫–æ–≥–æ–ª—é ‚Äî –≤ 39 —Å–ª—É—á–∞—è—Ö (beer_servings, spirit_servings, wine_servings, total_litres_of_pure_alcohol) –Ω–µ –ø–æ–¥—Ç—è–Ω—É–ª–∏—Å—å –∑–Ω–∞—á–µ–Ω–∏—è. –î–ª—è —ç—Ç–∏—Ö —Å—Ç—Ä–∞–Ω –Ω–µ—Ç –¥–∞–Ω–Ω—ã—Ö –≤ —Ç–∞–±–ª–∏—Ü–µ drinks, –ª–∏–±–æ –∫–æ–¥—ã —Å—Ç—Ä–∞–Ω –Ω–µ —Å–æ–≤–ø–∞–ª–∏.

–≠—Ç–∏ —Å—Ç—Ä–æ–∫–∏ –æ—Å—Ç–∞—é—Ç—Å—è –≤ –≥–ª–∞–≤–Ω–æ–π —Ç–∞–±–ª–∏—Ü–µ life_exp —Å NaN –≤ —Å—Ç–æ–ª–±—Ü–∞—Ö –∞–ª–∫–æ–≥–æ–ª—è. –≠—Ç–æ –Ω–æ—Ä–º–∞–ª—å–Ω—ã–π —Ä–µ–∑—É–ª—å—Ç–∞—Ç –¥–ª—è –ª–µ–≤–æ—Å—Ç–æ—Ä–æ–Ω–Ω–µ–≥–æ —Å–æ–µ–¥–∏–Ω–µ–Ω–∏—è ‚Äî –º—ã –Ω–µ —Ç–µ—Ä—è–µ–º –¥–∞–Ω–Ω—ã–µ –ø–æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏, –∞ –≤ –¥–∞–ª—å–Ω–µ–π—à–µ–º –ø—Ä–∏ –∞–Ω–∞–ª–∏–∑–µ –º–æ–∂–Ω–æ –ª–∏–±–æ –∏–≥–Ω–æ—Ä–∏—Ä–æ–≤–∞—Ç—å –ø—Ä–æ–ø—É—Å–∫–∏, –ª–∏–±–æ –∑–∞–ø–æ–ª–Ω—è—Ç—å –∏—Ö –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–π –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–µ–π, –µ—Å–ª–∏ –æ–Ω–∞ –µ—Å—Ç—å (–Ω–∞–ø—Ä–∏–º–µ—Ä, —á–µ—Ä–µ–∑ GNI –∏–ª–∏ —É—Å—Ä–µ–¥–Ω—ë–Ω–Ω—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏).

In [208]:
# —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –¥–∞—Ç–∞—Å–µ—Ç
merged_df.to_csv('life_expectancy_after_task_11.csv')

### 12

–û—Å—É—â–µ—Å—Ç–≤–∏—Ç–µ –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫—É –¥–∞–Ω–Ω—ã—Ö –ø–æ —Å—Ç—Ä–∞–Ω–∞–º –∏ —Ç–∏–ø—É –Ω–∞—É—á–Ω–æ–π —Å—Ç–∞—Ç—å–∏ (–º–Ω–æ–≥–æ–º–µ—Ä–Ω–∞—è –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∞). –í –∫–∞—á–µ—Å—Ç–≤–µ —Å—Ç–æ–ª–±—Ü–æ–≤ –∑–Ω–∞—á–µ–Ω–∏–π –¥–ª—è –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏ –≤–æ–∑—å–º–∏—Ç–µ –æ—Ü–µ–Ω–µ–Ω–Ω—É—é –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –∏ –æ–±—â–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –∞–ª–∫–æ–≥–æ–ª—è –≤ –ª–∏—Ç—Ä–∞—Ö. –í –∫–∞—á–µ—Å—Ç–≤–µ –∞–≥—Ä–µ–≥–≥–∏—Ä—É—é—â–∏—Ö —Ñ—É–Ω–∫—Ü–∏–π –¥–ª—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –≤–æ–∑—å–º–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ, –º–µ–¥–∏–∞–Ω—É, –º–∏–Ω–∏–º—É–º –∏ –º–∞–∫—Å–∏–º—É–º, –∞ –¥–ª—è –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è ‚Äî –∞–≥—Ä–µ–≥–≥–∏—Ä—É—é—â—É—é —Ñ—É–Ω–∫—Ü–∏—é/—Ñ—É–Ω–∫—Ü–∏–∏ –≤—ã–±–µ—Ä–∏—Ç–µ —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ. –ö–∞–∫ –≤—ã –º–æ–∂–µ—Ç–µ –ø—Ä–æ–∫–æ–º–º–µ–Ω—Ç–∏—Ä–æ–≤–∞—Ç—å —Å–≤–æ–π –≤—ã–±–æ—Ä –∏ —á—Ç–æ –≤—ã –Ω–∞–±–ª—é–¥–∞–µ—Ç–µ?

In [209]:
# –≥—Ä—É–ø–ø–∏—Ä—É–µ–º –ø–æ —Å—Ç—Ä–∞–Ω–∞–º –∏ —Ç–∏–ø—É –Ω–∞—É—á–Ω–æ–π —Å—Ç–∞—Ç—å–∏ –∏ –≤—ã—á–∏—Å–ª—è–µ–º –∞–≥–≥—Ä–µ–≥–∏—Ä—É—é—â–∏–µ —Ñ—É–Ω–∫—Ü–∏–∏

grouped = merged_df.groupby(['CountryCode', 'GhoCode']).agg(
    life_mean=('Numeric', 'mean'),
    life_median=('Numeric', 'median'),
    life_min=('Numeric', 'min'),
    life_max=('Numeric', 'max'),
    alcohol_mean=('total_litres_of_pure_alcohol', 'mean')
).reset_index()
grouped

,CountryCode,GhoCode,life_mean,life_median,life_min,life_max,alcohol_mean
0,AFG,WHOSIS_000001,56.311805,57.000000,49.0,61.97733,0.0
1,AFG,WHOSIS_000002,47.833333,48.800000,44.6,50.50000,0.0
2,AFG,WHOSIS_000015,15.223012,15.061535,13.0,17.00000,0.0
3,AGO,WHOSIS_000001,47.852151,48.500000,41.0,53.19343,5.9
4,AGO,WHOSIS_000002,42.444444,43.300000,37.9,45.60000,5.9
...,...,...,...,...,...,...,...
577,ZMB,WHOSIS_000002,44.900000,48.700000,34.6,51.40000,2.5
578,ZMB,WHOSIS_000015,16.068835,16.000000,14.0,18.10310,2.5
579,ZWE,WHOSIS_000001,55.186778,58.363385,42.0,64.00000,4.7
580,ZWE,WHOSIS_000002,45.222222,47.700000,36.4,51.80000,4.7
581,ZWE,WHOSIS_000015,17.369381,17.654040,15.0,19.00000,4.7

–î–ª—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ (Numeric) –±–µ—Ä—É mean, median, min –∏ max, —á—Ç–æ–±—ã –≤–∏–¥–µ—Ç—å —Å—Ä–µ–¥–Ω—é—é –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å, —Ü–µ–Ω—Ç—Ä–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ –∏ —Ä–∞–∑–±—Ä–æ—Å.

–î–ª—è –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è (total_litres_of_pure_alcohol) –±–µ—Ä—É mean, —Ç–∞–∫ –∫–∞–∫ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –Ω–∞ —á–µ–ª–æ–≤–µ–∫–∞ –≤ –∫–∞–∂–¥–æ–π —Å—Ç—Ä–∞–Ω–µ –∏ –¥–ª—è –∫–∞–∂–¥–æ–≥–æ —Ç–∏–ø–∞ —Å—Ç–∞—Ç—å–∏.

### 13

–í—Å—Ç–∞–≤—å—Ç–µ –ª—é–±—ã–µ –¥–≤–∞ —Å—Ç–æ–ª–±—Ü–∞ –∏–∑ –ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ –∑–∞–¥–∞–Ω–∏—è, –∫–æ—Ç–æ—Ä—ã–µ –≤—ã –ø–æ–ª—É—á–∏–ª–∏ –ø—É—Ç–µ–º –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏, –≤ –∏—Å—Ö–æ–¥–Ω—É—é —Ç–∞–±–ª–∏—Ü—É –≤ –∫–∞—á–µ—Å—Ç–≤–µ –¥–≤—É—Ö –Ω–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–æ–≤ (–Ω–∞–∑–≤–∞—Ç—å –≤—ã –∏—Ö –º–æ–∂–µ—Ç–µ –∫–∞–∫ —Ö–æ—Ç–∏—Ç–µ). –†–∞–∑—É–º–µ–µ—Ç—Å—è, –∑–Ω–∞—á–µ–Ω–∏—è —ç—Ç–∏—Ö —Å—Ç–æ–ª–±—Ü–æ–≤ –¥–æ–ª–∂–Ω—ã —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–æ–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏—è–º –∏—Å—Ö–æ–¥–Ω–æ–π —Ç–∞–±–ª–∏—Ü—ã –ø–æ —É–∫–∞–∑–∞–Ω–Ω—ã–º –≤ –ø—Ä–æ—à–ª–æ–º –∑–∞–¥–∞–Ω–∏–∏ –∫–∞—Ç–µ–≥–æ—Ä–∏—è–º.

*–ü—Ä–∏–º–µ—á–∞–Ω–∏–µ. –ù–µ –∑–∞–±—É–¥—å—Ç–µ —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –≤—Å–µ –∏–∑–º–µ–Ω–µ–Ω–∏—è! –í –ø–æ—Å–ª–µ–¥—É—é—â–∏—Ö –∑–∞–¥–∞–Ω–∏—è—Ö –≤—ã –¥–æ–ª–∂–Ω—ã —Ä–∞–±–æ—Ç–∞—Ç—å —Å –æ–±–Ω–æ–≤–ª–µ–Ω–Ω—ã–º –¥–∞—Ç–∞—Å–µ—Ç–æ–º.*

In [210]:
# —Ä–µ—à–∏–ª–∏ –≤—Å—Ç–∞–≤–∏—Ç—å life_mean –∏ alcohol_mean
columns_to_merge = grouped[['CountryCode', 'GhoCode', 'life_mean', 'alcohol_mean']]
life_exp = life_exp.merge(
    columns_to_merge,
    on=['CountryCode', 'GhoCode'],
    how='left'
)
life_exp = life_exp.rename(columns={
    'life_mean': 'avg_life_by_country',
    'alcohol_mean': 'avg_alcohol_by_country'
})
life_exp

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,DisplayValue,Numeric,avg_life_by_country,avg_alcohol_by_country
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,68,68.00000,72.667402,3.5
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,69,69.30000,69.911111,11.4
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,61,61.00000,61.567050,0.1
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,48,48.00000,50.473338,9.1
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,19,19.00000,19.895824,6.4
...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,68,68.00000,68.574297,0.5
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,16,16.00000,17.313487,6.9
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,51,51.00000,53.880190,4.3
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,64,63.50000,63.800000,4.9
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,71,71.02699,70.046697,3.8

dcs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

### 14

–ò—Å–ø–æ–ª—å–∑—É—è –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏, –∞—Ä–≥—É–º–µ–Ω—Ç–∏—Ä–æ–≤–∞–Ω–Ω–æ –æ—Ç–≤–µ—Ç—å—Ç–µ –Ω–∞ –≤–æ–ø—Ä–æ—Å: –Ω–∞ –∫–∞–∫–∏—Ö –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞—Ö —Å—Ä–µ–¥–Ω—è—è –æ–∂–∏–¥–∞–µ–º–∞—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –≤—ã—à–µ —É –º—É–∂—á–∏–Ω, –∞ –Ω–∞ –∫–∞–∫–∏—Ö —É –∂–µ–Ω—â–∏–Ω?

–ê –º–µ–¥–∏–∞–Ω–Ω–∞—è –æ–∂–∏–¥–∞–µ–º–∞—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å?

–ê –º–∏–Ω–∏–º–∞–ª—å–Ω–∞—è –æ–∂–∏–¥–∞–µ–º–∞—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å?

–°–¥–µ–ª–∞–π—Ç–µ –≤—ã–≤–æ–¥—ã!

*–ü–æ–¥—Å–∫–∞–∑–∫–∞. –ö–∞–∑–∞–ª–æ—Å—å –±—ã, –ø—Ä–∏ —á–µ–º –∑–¥–µ—Å—å —Ç–∏–ø –Ω–∞—É—á–Ω–æ–π —Å—Ç–∞—Ç—å–∏?*

In [211]:
# –≥—Ä—É–ø–ø–∏—Ä—É–µ–º –¥–ª—è –Ω–∞–≥–ª—è–¥–Ω–æ—Å—Ç–∏
grouped = life_exp.pivot_table(
    index=['RegionCode', 'SexCode'],
    columns='GhoCode',
    values='Numeric',
    aggfunc=['mean', 'median', 'min']
)
grouped

                            mean                                    median  \
GhoCode            WHOSIS_000001 WHOSIS_000002 WHOSIS_000015 WHOSIS_000001
RegionCode SexCode
AFR        BTSX        56.245705     49.136232     16.110551     57.000000
           FMLE        57.845527     50.094203     16.792841     58.000000
           MLE         54.724349     48.190580     15.331986     55.000000
AMR        BTSX        73.028041     63.838095     20.690960     74.000000
           FMLE        75.873706     65.971429     22.131179     77.000000
           MLE         70.282002     61.752381     19.175239     71.000000
EMR        BTSX        68.133069     59.192647     17.935767     70.365680
           FMLE        69.880894     59.848529     18.845779     73.000000
           MLE         66.595512     58.510294     17.199309     69.000000
EUR        BTSX        75.233666     66.658491     20.566757     76.000000
           FMLE        78.454599     69.118868     22.292036     79.000000
           MLE         71.976935     64.174214     18.476702     72.518745
SEAR       BTSX        66.345093     59.403030     17.360583     67.500000
           FMLE        68.188877     60.909091     18.342758     68.968250
           MLE         64.491738     57.942424     16.291729     65.000000
WPR        BTSX        70.985250     62.924691     18.785198     71.000000
           FMLE        73.538356     64.733333     20.359732     73.500000
           MLE         68.585153     61.219753     17.236480     68.124050

                                                         min                \
GhoCode            WHOSIS_000002 WHOSIS_000015 WHOSIS_000001 WHOSIS_000002
RegionCode SexCode
AFR        BTSX            49.35      16.00000          38.0          33.1
           FMLE            50.00      16.94181          38.0          33.4
           MLE             48.80      15.14800          38.0          32.8
AMR        BTSX            63.80      21.00000          54.0          47.8
           FMLE            66.20      22.53821          56.0          48.5
           MLE             62.10      19.34305          52.0          47.1
EMR        BTSX            61.65      18.00000          42.0          41.6
           FMLE            63.10      18.89404          44.0          42.0
           MLE             60.80      17.00000          41.0          41.0
EUR        BTSX            67.40      20.11892          62.0          54.3
           FMLE            70.00      22.00000          65.0          56.6
           MLE             64.80      18.00000          58.0          51.2
SEAR       BTSX            58.90      17.00000          50.0          50.0
           FMLE            59.90      18.00000          51.0          51.2
           MLE             58.20      16.00000          48.0          48.8
WPR        BTSX            62.20      18.00000          53.0          50.2
           FMLE            63.70      19.00000          54.0          51.8
           MLE             60.80      16.65897          51.0          48.6


GhoCode            WHOSIS_000015
RegionCode SexCode
AFR        BTSX         11.00000
           FMLE         11.00000
           MLE          11.00000
AMR        BTSX         15.00000
           FMLE         16.00000
           MLE          12.86658
EMR        BTSX         14.00000
           FMLE         14.00000
           MLE          13.00000
EUR        BTSX         15.00000
           FMLE         16.00000
           MLE          12.00000
SEAR       BTSX         13.00000
           FMLE         12.00000
           MLE          12.00000
WPR        BTSX         13.00000
           FMLE         15.00000
           MLE          12.00000

–ï—Å–ª–∏ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ –¥–∞–Ω–Ω—ã–µ –ø–æ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏, —Å—Ç–∞–Ω–æ–≤–∏—Ç—Å—è –∑–∞–º–µ—Ç–Ω–æ, —á—Ç–æ –∂–µ–Ω—â–∏–Ω—ã –≤ —Å—Ä–µ–¥–Ω–µ–º –∂–∏–≤—É—Ç –¥–æ–ª—å—à–µ –º—É–∂—á–∏–Ω –Ω–∞ –≤—Å–µ—Ö –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞—Ö. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤ –ê—Ñ—Ä–∏–∫–µ —Å—Ä–µ–¥–Ω—è—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –æ–∫–æ–ª–æ 57,8 –ª–µ—Ç, –∞ –º—É–∂—á–∏–Ω ‚Äî 54,7 –ª–µ—Ç, —Ä–∞–∑–Ω–∏—Ü–∞ –ø—Ä–∏–º–µ—Ä–Ω–æ 3 –≥–æ–¥–∞. –í –ê–º–µ—Ä–∏–∫–µ –∂–µ–Ω—â–∏–Ω—ã –∂–∏–≤—É—Ç –≤ —Å—Ä–µ–¥–Ω–µ–º 75,9 –ª–µ—Ç, –º—É–∂—á–∏–Ω—ã ‚Äî 70,3, –∞ –≤ –ï–≤—Ä–æ–ø–µ ‚Äî 78,5 –ø—Ä–æ—Ç–∏–≤ 72 –ª–µ—Ç. –ü—Ä–∏—á—ë–º —ç—Ç–∞ —Ç–µ–Ω–¥–µ–Ω—Ü–∏—è —Å–æ—Ö—Ä–∞–Ω—è–µ—Ç—Å—è, –Ω–µ–∑–∞–≤–∏—Å–∏–º–æ –æ—Ç —Ç–æ–≥–æ, –∫–∞–∫–æ–π —Ç–∏–ø —Å—Ç–∞—Ç—å–∏ —É—á–∏—Ç—ã–≤–∞–µ—Ç—Å—è ‚Äî –±—É–¥—å —Ç–æ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏ —Å —Ä–æ–∂–¥–µ–Ω–∏—è, –ø–æ—Å–ª–µ 60 –ª–µ—Ç –∏–ª–∏ –æ–∂–∏–¥–∞–µ–º–∞—è –∑–¥–æ—Ä–æ–≤–∞—è –∂–∏–∑–Ω—å.

–ï—Å–ª–∏ —Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ –º–µ–¥–∏–∞–Ω—É, –∫–∞—Ä—Ç–∏–Ω–∞ –ø–æ—á—Ç–∏ —Ç–∞–∫–∞—è –∂–µ: —É –∂–µ–Ω—â–∏–Ω –æ–Ω–∞ –≤—ã—à–µ, —á–µ–º —É –º—É–∂—á–∏–Ω, –Ω–∞ –≤—Å–µ—Ö –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞—Ö. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤ –ê–º–µ—Ä–∏–∫–µ –º–µ–¥–∏–∞–Ω–∞ –¥–ª—è –∂–µ–Ω—â–∏–Ω 77 –ª–µ—Ç, –¥–ª—è –º—É–∂—á–∏–Ω 71, –≤ –ï–≤—Ä–æ–ø–µ ‚Äî 79 –ø—Ä–æ—Ç–∏–≤ 72,5 –≥–æ–¥–∞.

–ú–∏–Ω–∏–º–∞–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è —Ç–æ–∂–µ —á–∞—â–µ –≤—ã—à–µ —É –∂–µ–Ω—â–∏–Ω –∏–ª–∏ –ø—Ä–∏–º–µ—Ä–Ω–æ —Ä–∞–≤–Ω—ã –º—É–∂—á–∏–Ω–∞–º. –†–∞–∑–Ω–∏—Ü–∞ –∑–¥–µ—Å—å –º–µ–Ω—å—à–µ, –ø–æ—Ç–æ–º—É —á—Ç–æ –º–∏–Ω–∏–º—É–º—ã –∑–∞–≤–∏—Å—è—Ç –æ—Ç –æ—Ç–¥–µ–ª—å–Ω—ã—Ö —ç–∫—Å—Ç—Ä–µ–º–∞–ª—å–Ω—ã—Ö —Å–ª—É—á–∞–µ–≤, –∞ –Ω–µ –æ—Ç –æ–±—â–µ–π —Ç–µ–Ω–¥–µ–Ω—Ü–∏–∏. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤ –ê—Ñ—Ä–∏–∫–µ –º–∏–Ω–∏–º–∞–ª—å–Ω–∞—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –±–µ–∑ –±–æ–ª–µ–∑–Ω–µ–π –¥–ª—è –∂–µ–Ω—â–∏–Ω 33,4 –≥–æ–¥–∞, –¥–ª—è –º—É–∂—á–∏–Ω 32,8; –≤ –ê–º–µ—Ä–∏–∫–µ ‚Äî 48,5 –ø—Ä–æ—Ç–∏–≤ 47,1 –≥–æ–¥–∞.

–í —Ü–µ–ª–æ–º –º–æ–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å –≤—ã–≤–æ–¥, —á—Ç–æ –Ω–∞ –≤—Å–µ—Ö –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞—Ö –∂–µ–Ω—â–∏–Ω—ã –∂–∏–≤—É—Ç –¥–æ–ª—å—à–µ –º—É–∂—á–∏–Ω. –†–∞–∑—Ä—ã–≤ –æ—Å–æ–±–µ–Ω–Ω–æ –∑–∞–º–µ—Ç–µ–Ω –≤ —Å—Ä–µ–¥–Ω–µ–º –∏ –º–µ–¥–∏–∞–Ω–Ω–æ–º –∑–Ω–∞—á–µ–Ω–∏–∏, –∞ –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏ –º–µ–Ω–µ–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—å–Ω—ã. –ê–Ω–∞–ª–∏–∑ —Ä–∞–∑–Ω—ã—Ö —Ç–∏–ø–æ–≤ —Å—Ç–∞—Ç–µ–π –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–∞–µ—Ç —ç—Ç—É –∑–∞–∫–æ–Ω–æ–º–µ—Ä–Ω–æ—Å—Ç—å ‚Äî –¥–∞–Ω–Ω—ã–µ —Å–æ–≥–ª–∞—Å–æ–≤–∞–Ω—ã –º–µ–∂–¥—É —Å–æ–±–æ–π.

### 15

–†–∞–±–æ—Ç–∞—è –ª–∏—à—å —Å –æ–±—â–∏–º –æ–±—ä–µ–¥–∏–Ω–µ–Ω–Ω—ã–º –¥–∞—Ç–∞—Å–µ—Ç–æ–º –∏ –Ω–µ –∏—Å–ø–æ–ª—å–∑—É—è –∏—Å—Ö–æ–¥–Ω—É—é —Ç–∞–±–ª–∏—Ü—É `drinks`, –ø–æ–¥—Å—á–∏—Ç–∞–π—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –∫–∞–∂–¥–æ–≥–æ –≤–∏–¥–∞ –∞–ª–∫–æ–≥–æ–ª—è –∏ —Å—Ä–µ–¥–Ω–µ–µ –æ–±—â–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ª–∏—Ç—Ä–æ–≤ –ø–æ—Ç—Ä–µ–±–ª—è–µ–º–æ–≥–æ –∞–ª–∫–æ–≥–æ–ª—è –Ω–∞ —á–µ–ª–æ–≤–µ–∫–∞ –ø–æ –≤—Å–µ–º –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞–º. –ó–∞–Ω–µ—Å–∏—Ç–µ –≤–∞—à–∏ —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã –≤ –æ—Ç–¥–µ–ª—å–Ω—ã–π –¥–∞—Ç–∞—Ñ—Ä–µ–π–º!

*–ü–æ–¥—Å–∫–∞–∑–∫–∞. –ó–∞–¥–∞—á–∞ –Ω–µ–º–Ω–æ–≥–æ —Å–ª–æ–∂–Ω–µ–µ, —á–µ–º –º–æ–∂–µ—Ç –ø–æ–∫–∞–∑–∞—Ç—å—Å—è –Ω–∞ –ø–µ—Ä–≤—ã–π –≤–∑–≥–ª—è–¥ ‚Äî –≤ –æ–±—ä–µ–¥–∏–Ω–µ–Ω–Ω–æ–º –¥–∞—Ç–∞—Å–µ—Ç–µ —Å—Ç—Ä–∞–Ω—ã –≤—Å—Ç—Ä–µ—á–∞—é—Ç—Å—è —Ä–∞–∑–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–∞–∑, –∏ –∏–∑-–∑–∞ —ç—Ç–æ–≥–æ –º–æ–≥—É—Ç –≤–æ–∑–Ω–∏–∫–Ω—É—Ç—å –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã–µ –ø—Ä–æ–±–ª–µ–º—ã. –ï—Å–ª–∏ —Ç–∞–∫ —Å–ª—É—á–∏—Ç—Å—è, –Ω–∞–¥–æ –ø–æ–¥—É–º–∞—Ç—å, –∫–∞–∫ —ç—Ç–æ –æ–±–æ–π—Ç–∏!*

*–ü—Ä–∏–º–µ—á–∞–Ω–∏–µ. –†–∞–∑—É–º–µ–µ—Ç—Å—è, —ç—Ç–æ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —Å–¥–µ–ª–∞—Ç—å –∞–≤—Ç–æ–º–∞—Ç–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω–æ, –∞ –Ω–µ –ø–µ—Ä–µ–±–∏—Ä–∞—è –∫–∞–∂–¥—ã–π –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç –ø–æ –æ—Ç–¥–µ–ª—å–Ω–æ—Å—Ç–∏.*

In [212]:
# —Å–Ω–∞—á–∞–ª–∞ –Ω–∞—Ö–æ–¥–∏–º —Å—Ä–µ–¥–Ω–∏–µ –∑–Ω–∞—á–µ–Ω–∏—è –ø–æ —Å—Ç—Ä–∞–Ω–∞–º
country_avg = merged_df.groupby(['RegionCode', 'CountryCode'])[
    ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
].mean()
# –ø–æ—Ç–æ–º —Å—Ä–µ–¥–Ω–∏–µ –∑–Ω–∞—á–µ–Ω–∏—è –ø–æ —Ä–µ–≥–∏–æ–Ω–∞–º
continent_avg = country_avg.groupby('RegionCode')[
    ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
].mean()
continent_avg

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
RegionCode,,,,
AFR,68.826087,17.304348,18.000000,3.360870
AMR,155.600000,148.257143,37.514286,6.102857
EMR,10.428571,21.190476,4.857143,0.714286
EUR,175.132075,130.415094,123.528302,7.873585
SEAR,14.818182,44.090909,0.454545,1.063636
WPR,81.962963,66.851852,27.740741,3.637037

–î–∞—Ç–∞—Ñ—Ä–µ–π–º —É—Å–ø–µ—à–Ω–æ —Å–æ–∑–¥–∞–Ω

### 16

–°–æ–∑–¥–∞–Ω–∏–µ –Ω–æ–≤—ã—Ö –ø—Ä–∏–∑–Ω–∞–∫–æ–≤ (feature engineering) —è–≤–ª—è–µ—Ç—Å—è –æ–¥–Ω–∏–º –∏–∑ –æ—Å–Ω–æ–≤–Ω—ã—Ö —Å—Ä–µ–¥—Å—Ç–≤ —É–ª—É—á—à–µ–Ω–∏—è –∫–∞—á–µ—Å—Ç–≤–∞ —Ä–∞–±–æ—Ç—ã –∞–ª–≥–æ—Ä–∏—Ç–º–æ–≤ –º–∞—à–∏–Ω–Ω–æ–≥–æ –æ–±—É—á–µ–Ω–∏—è –Ω–∞ —ç—Ç–∞–ø–µ –æ–±—Ä–∞–±–æ—Ç–∫–∏ –¥–∞–Ω–Ω—ã—Ö, –∞ —Ç–∞–∫–∂–µ –æ—Ç–ª–∏—á–Ω—ã–π —Å–ø–æ—Å–æ–± —É–≤–µ–ª–∏—á–∏—Ç—å –≥–ª—É–±–∏–Ω—É –≤–∞—à–∏—Ö –≤—ã–≤–æ–¥–æ–≤ –∏–∑ –ø—Ä–æ–¥–µ–ª–∞–Ω–Ω–æ–≥–æ –∞–Ω–∞–ª–∏–∑–∞ –≤ —Ü–µ–ª–æ–º! –ß–∞—Å—Ç–∏—á–Ω–æ –º—ã —Å –≤–∞–º–∏ —É–∂–µ –æ—Å—É—â–µ—Å—Ç–≤–ª—è–ª–∏ feature engineering, –∫–æ–≥–¥–∞ –¥–æ–±–∞–≤–ª—è–ª–∏ –Ω–æ–≤—ã–µ —Å—Ç–æ–ª–±—Ü—ã –≤ –∑–∞–¥–∞–Ω–∏–∏ 13.

–¢–µ–ø–µ—Ä—å –¥–∞–≤–∞–π—Ç–µ –¥–æ–±–∞–≤–∏–º –≤ —Ç–∞–±–ª–∏—Ü—É —Å—Ç–æ–ª–±–µ—Ü, –∫–æ—Ç–æ—Ä—ã–π –±—É–¥–µ—Ç –ø–æ–∫–∞–∑—ã–≤–∞—Ç—å, –∫–∞–∫–æ–µ –æ–±—â–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ servings per person –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –≤ —Å—Ä–µ–¥–Ω–µ–º –ø–æ —Å—Ç—Ä–∞–Ω–µ, –∫ –∫–æ—Ç–æ—Ä–æ–π –æ—Ç–Ω–æ—Å–∏—Ç—Å—è –Ω–∞—É—á–Ω–∞—è —Å—Ç–∞—Ç—å—è. –°—Ç–æ–ª–±–µ—Ü –¥–ª—è —ç—Ç–æ–≥–æ –ø—Ä–∏–∑–Ω–∞–∫–∞ –Ω–∞–∑–æ–≤–∏—Ç–µ `total_servings`.

–ß–µ–º –º–æ–∂–µ—Ç –±—ã—Ç—å –ø–æ–ª–µ–∑–µ–Ω —Ç–∞–∫–æ–π –ø—Ä–∏–∑–Ω–∞–∫?

***–ë–æ–Ω—É—Å (2 –±–æ–Ω. –±–∞–ª–ª–∞):*** –ü—Ä–∏–¥—É–º–∞–π—Ç–µ –µ—â–µ –∫–∞–∫–æ–π-–Ω–∏–±—É–¥—å —Å–≤–æ–π –æ—Å–º—ã—Å–ª–µ–Ω–Ω—ã–π –ø—Ä–∏–∑–Ω–∞–∫, –∫–æ—Ç–æ—Ä—ã–π –º–æ–∂–µ—Ç –±—ã—Ç—å –ø–æ–ª–µ–∑–µ–Ω –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞ (–Ω–µ—Å–µ—Ç –≤ —Å–µ–±–µ –∫–∞–∫—É—é-—Ç–æ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é), –∏ –¥–æ–±–∞–≤—å—Ç–µ –µ–≥–æ –≤ —Ç–∞–±–ª–∏—Ü—É. –û–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –∞—Ä–≥—É–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ, —á–µ–º –ø–æ–ª–µ–∑–µ–Ω –≤–∞—à –ø—Ä–∏–∑–Ω–∞–∫.

In [213]:
# —Å–æ–∑–¥–∞–µ–º total_servings
merged_df['total_servings'] = merged_df.groupby('CountryCode')[
    ['beer_servings', 'spirit_servings', 'wine_servings']
].transform('mean').sum(axis=1)

merged_df

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,total_servings
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,68,68.00000,78.0,118.0,1.0,3.5,197.0
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,69,69.30000,313.0,118.0,165.0,11.4,596.0
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,61,61.00000,6.0,0.0,0.0,0.1,6.0
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,48,48.00000,42.0,5.0,2.0,9.1,49.0
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,19,19.00000,99.0,258.0,1.0,6.4,358.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,68,68.00000,12.0,6.0,10.0,0.5,28.0
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,16,16.00000,306.0,63.0,23.0,6.9,392.0
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,51,51.00000,25.0,7.0,7.0,4.3,39.0
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,64,63.50000,89.0,132.0,54.0,4.9,275.0
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,71,71.02699,21.0,179.0,11.0,3.8,211.0

docs:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html

–¢–∞–∫–æ–π –ø—Ä–∏–∑–Ω–∞–∫ –ø–æ–ª–µ–∑–µ–Ω –≤:

–°—Ä–∞–≤–Ω–µ–Ω–∏–∏ —Å—Ç—Ä–∞–Ω ‚Äì –º–æ–∂–Ω–æ —Å—Ä–∞–∑—É —É–≤–∏–¥–µ—Ç—å, –≥–¥–µ –≤ —Å—Ä–µ–¥–Ω–µ–º –ø—å—é—Ç –±–æ–ª—å—à–µ, –±–µ–∑ —Ä–∞–∑–±–∏–µ–Ω–∏—è –ø–æ –≤–∏–¥–∞–º –∞–ª–∫–æ–≥–æ–ª—è

–í–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è –∏ –∞–Ω–∞–ª–∏–∑ ‚Äì —É–¥–æ–±–Ω–æ —Å—Ç—Ä–æ–∏—Ç—å –≥—Ä–∞—Ñ–∏–∫–∏ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –æ—Ç —Å—Ä–µ–¥–Ω–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∏ –Ω–∞–æ–±–æ—Ä–æ—Ç

–ú–æ–∂–Ω–æ –∞–Ω–∞–ª–∏–∑–∏—Ä–æ–≤–∞—Ç—å —Å–≤—è–∑—å –º–µ–∂–¥—É –æ–±—â–∏–º –∞–ª–∫–æ–≥–æ–ª–µ–º –∏ –¥—Ä—É–≥–∏–º–∏ —Å–æ—Ü–∏–∞–ª—å–Ω–æ-—ç–∫–æ–Ω–æ–º–∏—á–µ—Å–∫–∏–º–∏ –ø–æ–∫–∞–∑–∞—Ç–µ–ª—è–º–∏

–î–æ–±–∞–≤–∏–º –æ—Ç —Å–µ–±—è –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–π –ø—Ä–∏–∑–Ω–∞–∫ - –¥–æ–ª—é —Ç–∏–ø–æ–≤ –∞–ª–∫–æ–≥–æ–ª—è, –∫–æ—Ç–æ—Ä—ã–µ –ø–æ—Ç—Ä–µ–±–ª—è—é—Ç—Å—è –≤ —Å—Ç—Ä–∞–Ω–µ

In [214]:
merged_df['alcohol_diversity'] = merged_df[['beer_servings', 'spirit_servings', 'wine_servings']].gt(0).sum(axis=1) / 3
merged_df

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,total_servings,alcohol_diversity
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,68,68.00000,78.0,118.0,1.0,3.5,197.0,1.000000
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,69,69.30000,313.0,118.0,165.0,11.4,596.0,1.000000
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,61,61.00000,6.0,0.0,0.0,0.1,6.0,0.333333
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,48,48.00000,42.0,5.0,2.0,9.1,49.0,1.000000
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,19,19.00000,99.0,258.0,1.0,6.4,358.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,68,68.00000,12.0,6.0,10.0,0.5,28.0,1.000000
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,16,16.00000,306.0,63.0,23.0,6.9,392.0,1.000000
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,51,51.00000,25.0,7.0,7.0,4.3,39.0,1.000000
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,64,63.50000,89.0,132.0,54.0,4.9,275.0,1.000000
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,71,71.02699,21.0,179.0,11.0,3.8,211.0,1.000000

docs:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.gt.html

–≠—Ç–æ –ø–æ–ª–µ–∑–Ω–æ, –ø–æ—Ç–æ–º—É —á—Ç–æ:

–ü–æ–∫–∞–∑—ã–≤–∞–µ—Ç —Ä–∞–∑–Ω–æ–æ–±—Ä–∞–∑–∏–µ –∞–ª–∫–æ–≥–æ–ª—å–Ω–æ–π –∫—É–ª—å—Ç—É—Ä—ã –≤ —Å—Ç—Ä–∞–Ω–µ

–ú–æ–∂–µ—Ç –±—ã—Ç—å —Å–≤—è–∑–∞–Ω–æ —Å –æ–±—Ä–∞–∑–æ–º –∂–∏–∑–Ω–∏ –∏ —Å–æ—Ü–∏–∞–ª—å–Ω—ã–º–∏ –ø—Ä–∏–≤—ã—á–∫–∞–º–∏, –∞ –∑–Ω–∞—á–∏—Ç ‚Äî –∫–æ—Å–≤–µ–Ω–Ω–æ —Å –æ–∂–∏–¥–∞–µ–º–æ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏

–û—Ç–ª–∏—á–∞–µ—Ç—Å—è –æ—Ç total_servings –∏–ª–∏ total_litres_of_pure_alcohol, –∫–æ—Ç–æ—Ä—ã–µ —É—á–∏—Ç—ã–≤–∞—é—Ç –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ, –∞ –Ω–µ —Ä–∞–∑–Ω–æ–æ–±—Ä–∞–∑–∏–µ, —á—Ç–æ —Å–æ–∑–¥–∞–µ—Ç –µ—â—ë –æ–¥–Ω—É —Å—Ç–æ—Ä–æ–Ω—É –¥–ª—è –≤–∑–≥–ª—è–¥–∞ –∏ –∞–Ω–∞–ª–∏–∑–∞

### 17

–ï—Å—Ç—å –ª–∏ –≤ –¥–∞–Ω–Ω—ã—Ö –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏, –∫–æ—Ç–æ—Ä—ã–µ –ø—Ä–∏–Ω–∏–º–∞—é—Ç –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç—Ä–æ–∫, –∞ –Ω–µ —á–∏—Å–µ–ª? –ï—Å–ª–∏ –¥–∞, —Ç–æ –¥–ª—è –º–Ω–æ–≥–∏—Ö –∞–ª–≥–æ—Ä–∏—Ç–º–æ–≤ —ç—Ç–æ –º–æ–∂–µ—Ç —Å—Ç–∞—Ç—å —Å–µ—Ä—å–µ–∑–Ω—ã–º –ø—Ä–µ–ø—è—Ç—Å—Ç–≤–∏–µ–º, –ø–æ—ç—Ç–æ–º—É –∑–∞–∫–æ–¥–∏—Ä—É–π—Ç–µ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏ —Ç–∞–∫, —á—Ç–æ–±—ã –∫ –¥–∞–Ω–Ω—ã–º –º–æ–∂–Ω–æ –±—ã–ª–æ –ø—Ä–∏–º–µ–Ω–∏—Ç—å –ª—é–±—ã–µ –∞–ª–≥–æ—Ä–∏—Ç–º—ã. –ê—Ä–≥—É–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ –≤—ã–±–æ—Ä –º–µ—Ç–æ–¥–æ–≤ –∫–æ–¥–∏—Ä–æ–≤–∞–Ω–∏—è.

*–ü–æ–¥—Å–∫–∞–∑–∫–∞. –í–∞–º –º–æ–≥—É—Ç –ø–æ–º–æ—á—å Label encoding –∏ One-Hot Encoding. –ù–æ –±—É–¥—å—Ç–µ –≤–Ω–∏–º–∞—Ç–µ–ª—å–Ω—ã! –£ –∫–∞–∂–¥–æ–≥–æ –∏–∑ —ç—Ç–∏—Ö –º–µ—Ç–æ–¥–æ–≤ –µ—Å—Ç—å —Å–≤–æ–∏ —Å–∏–ª—å–Ω—ã–µ –∏ —Å–ª–∞–±—ã–µ —Å—Ç–æ—Ä–æ–Ω—ã, –∞ —Ç–∞–∫–∂–µ –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–∏—è –ø—Ä–∏–º–µ–Ω–∏–º–æ—Å—Ç–∏.*

–ë–µ–∑—É—Å–ª–æ–≤–Ω–æ –µ—Å—Ç—å –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–µ –ø—Ä–∏–∑–Ω–∞–∫–∏, –∫–æ—Ç–æ—Ä—ã–µ –ø—Ä–∏–Ω–∏–º–∞—é—Ç –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ç—Ä–æ–∫, –∞ –Ω–µ —á–∏—Å–µ–ª

In [215]:
# –∫–æ–¥–∏—Ä—É–µ–º GhoCode, Sex, Region, IncomeGroup
categorical_cols = ['GhoCode', 'RegionCode', 'WorldBankIncomeGroupGroupCode', 'SexCode']
encoded_df = pd.get_dummies(merged_df, columns=categorical_cols, prefix=categorical_cols)
encoded_df

,YearCode,CountryCode,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,total_servings,alcohol_diversity,...,RegionCode_EUR,RegionCode_SEAR,RegionCode_WPR,WorldBankIncomeGroupGroupCode_WB_HI,WorldBankIncomeGroupGroupCode_WB_LI,WorldBankIncomeGroupGroupCode_WB_LMI,WorldBankIncomeGroupGroupCode_WB_UMI,SexCode_BTSX,SexCode_FMLE,SexCode_MLE
0,1990,NIC,68,68.00000,78.0,118.0,1.0,3.5,197.0,1.000000,...,False,False,False,False,False,True,False,False,False,True
1,2012,IRL,69,69.30000,313.0,118.0,165.0,11.4,596.0,1.000000,...,True,False,False,True,False,False,False,False,False,True
2,2000,YEM,61,61.00000,6.0,0.0,0.0,0.1,6.0,0.333333,...,False,False,False,False,True,False,False,True,False,False
3,2000,NGA,48,48.00000,42.0,5.0,2.0,9.1,49.0,1.000000,...,False,False,False,False,False,True,False,False,True,False
4,1990,THA,19,19.00000,99.0,258.0,1.0,6.4,358.0,1.000000,...,False,True,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,2000,MAR,68,68.00000,12.0,6.0,10.0,0.5,28.0,1.000000,...,False,False,False,False,False,True,False,True,False,False
6404,1990,PLW,16,16.00000,306.0,63.0,23.0,6.9,392.0,1.000000,...,False,False,True,False,False,False,True,True,False,False
6405,1990,BFA,51,51.00000,25.0,7.0,7.0,4.3,39.0,1.000000,...,False,False,False,False,True,False,False,False,True,False
6406,2012,ALB,64,63.50000,89.0,132.0,54.0,4.9,275.0,1.000000,...,True,False,False,False,False,True,False,False,False,True
6407,2013,ARM,71,71.02699,21.0,179.0,11.0,3.8,211.0,1.000000,...,True,False,False,False,False,True,False,True,False,False

docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

–ê—Ä–≥—É–º–µ–Ω—Ç–∞—Ü–∏—è:

–£ –Ω–∞—Å –µ—Å—Ç—å –Ω–µ—Å–∫–æ–ª—å–∫–æ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã—Ö –ø—Ä–∏–∑–Ω–∞–∫–æ–≤: GhoCode, RegionCode, WorldBankIncomeGroupGroupCode –∏ SexCode. –û–Ω–∏ —Ö—Ä–∞–Ω—è—Ç —Ç–µ–∫—Å—Ç–æ–≤—ã–µ –º–µ—Ç–∫–∏, –∞ –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–æ –∞–ª–≥–æ—Ä–∏—Ç–º–æ–≤ –º–∞—à–∏–Ω–Ω–æ–≥–æ –æ–±—É—á–µ–Ω–∏—è —Ä–∞–±–æ—Ç–∞—Ç—å —Å —Ç–µ–∫—Å—Ç–æ–º –Ω–∞–ø—Ä—è–º—É—é –Ω–µ —É–º–µ—é—Ç. –ü–æ—ç—Ç–æ–º—É –º—ã –∏—Ö –∫–æ–¥–∏—Ä—É–µ–º. –Ø –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–ª One-Hot Encoding, –ø–æ—Ç–æ–º—É —á—Ç–æ —É —ç—Ç–∏—Ö –ø—Ä–∏–∑–Ω–∞–∫–æ–≤ –Ω–µ—Ç –µ—Å—Ç–µ—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –ø–æ—Ä—è–¥–∫–∞ ‚Äî –Ω–µ–ª—å–∑—è —Å–∫–∞–∑–∞—Ç—å, —á—Ç–æ –æ–¥–Ω–∞ –∫–∞—Ç–µ–≥–æ—Ä–∏—è ¬´–±–æ–ª—å—à–µ¬ª –∏–ª–∏ ¬´–º–µ–Ω—å—à–µ¬ª –¥—Ä—É–≥–æ–π. One-Hot –ø—Ä–µ–≤—Ä–∞—â–∞–µ—Ç –∫–∞–∂–¥—É—é –∫–∞—Ç–µ–≥–æ—Ä–∏—é –≤ –æ—Ç–¥–µ–ª—å–Ω—ã–π –±–∏–Ω–∞—Ä–Ω—ã–π —Å—Ç–æ–ª–±–µ—Ü, –∏ –∞–ª–≥–æ—Ä–∏—Ç–º—ã –º–æ–≥—É—Ç –∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ —Ä–∞–±–æ—Ç–∞—Ç—å —Å —ç—Ç–∏–º–∏ –ø—Ä–∏–∑–Ω–∞–∫–∞–º–∏, –Ω–µ –≤–≤–æ–¥—è –ª–∏—à–Ω—é—é –ª–æ–≥–∏–∫—É. –¢–∞–∫ –ø—Ä–æ—â–µ –∏ –±–µ–∑–æ–ø–∞—Å–Ω–µ–µ –¥–ª—è –∞–Ω–∞–ª–∏–∑–∞ –∏ –ø–æ—Å—Ç—Ä–æ–µ–Ω–∏—è –º–æ–¥–µ–ª–µ–π.

In [216]:
# –∫–æ–¥–∏—Ä—É–µ–º —Å—Ç—Ä–∞–Ω—ã
unique_countries = merged_df['CountryCode'].unique()
country_label_dict = {country: i for i, country in enumerate(unique_countries)}
merged_df['CountryCode_encoded'] = merged_df['CountryCode'].map(country_label_dict)
merged_df

,GhoCode,YearCode,RegionCode,WorldBankIncomeGroupGroupCode,CountryCode,SexCode,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,total_servings,alcohol_diversity,CountryCode_encoded
0,WHOSIS_000001,1990,AMR,WB_LMI,NIC,MLE,68,68.00000,78.0,118.0,1.0,3.5,197.0,1.000000,0
1,WHOSIS_000002,2012,EUR,WB_HI,IRL,MLE,69,69.30000,313.0,118.0,165.0,11.4,596.0,1.000000,1
2,WHOSIS_000001,2000,EMR,WB_LI,YEM,BTSX,61,61.00000,6.0,0.0,0.0,0.1,6.0,0.333333,2
3,WHOSIS_000001,2000,AFR,WB_LMI,NGA,FMLE,48,48.00000,42.0,5.0,2.0,9.1,49.0,1.000000,3
4,WHOSIS_000015,1990,SEAR,WB_LMI,THA,FMLE,19,19.00000,99.0,258.0,1.0,6.4,358.0,1.000000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6403,WHOSIS_000001,2000,EMR,WB_LMI,MAR,BTSX,68,68.00000,12.0,6.0,10.0,0.5,28.0,1.000000,190
6404,WHOSIS_000015,1990,WPR,WB_UMI,PLW,BTSX,16,16.00000,306.0,63.0,23.0,6.9,392.0,1.000000,90
6405,WHOSIS_000001,1990,AFR,WB_LI,BFA,FMLE,51,51.00000,25.0,7.0,7.0,4.3,39.0,1.000000,153
6406,WHOSIS_000002,2012,EUR,WB_LMI,ALB,MLE,64,63.50000,89.0,132.0,54.0,4.9,275.0,1.000000,191
6407,WHOSIS_000001,2013,EUR,WB_LMI,ARM,BTSX,71,71.02699,21.0,179.0,11.0,3.8,211.0,1.000000,35

–ê—Ä–≥—É–º–µ–Ω—Ç–∞—Ü–∏—è:

–î–ª—è –ø—Ä–∏–∑–Ω–∞–∫–∞ CountryCode –º—ã –ø—Ä–∏–º–µ–Ω—è–µ–º Label Encoding, –ø–æ—Ç–æ–º—É —á—Ç–æ –∫–∞–∂–¥–∞—è —Å—Ç—Ä–∞–Ω–∞ —É–Ω–∏–∫–∞–ª—å–Ω–∞ –∏ –∏—Ö —Å–ª–∏—à–∫–æ–º –º–Ω–æ–≥–æ –¥–ª—è –ø—Ä–∏–º–µ–Ω–µ–Ω–∏—è One-Hot Encoding. –ï—Å–ª–∏ –±—ã –º—ã —Å–¥–µ–ª–∞–ª–∏ One-Hot, –ø–æ–ª—É—á–∏—Ç—Å—è –æ–≥—Ä–æ–º–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –Ω–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–æ–≤, —á—Ç–æ —Å–∏–ª—å–Ω–æ —Ä–∞–∑–¥—É–µ—Ç –¥–∞—Ç–∞—Å–µ—Ç –∏ —É—Å–ª–æ–∂–Ω–∏—Ç —Ä–∞–±–æ—Ç—É –∞–ª–≥–æ—Ä–∏—Ç–º–æ–≤. –ü—Ä–∏ Label Encoding –∫–∞–∂–¥–∞—è —Å—Ç—Ä–∞–Ω–∞ –ø–æ–ª—É—á–∞–µ—Ç —É–Ω–∏–∫–∞–ª—å–Ω—ã–π —á–∏—Å–ª–æ–≤–æ–π –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä, –∫–æ—Ç–æ—Ä—ã–π –º–æ–¥–µ–ª–∏ –º–æ–≥—É—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –∫–∞–∫ –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—É—é –º–µ—Ç–∫—É –±–µ–∑ —Å–æ–∑–¥–∞–Ω–∏—è –ª–∏—à–Ω–∏—Ö –∫–æ–ª–æ–Ω–æ–∫.

–í–∞–∂–Ω–æ –ø–æ–Ω–∏–º–∞—Ç—å, —á—Ç–æ —á–∏—Å–ª–∞ –Ω–µ –Ω–µ—Å—É—Ç –ø–æ—Ä—è–¥–∫–æ–≤–æ–π –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ ‚Äî —ç—Ç–æ –∏–º–µ–Ω–Ω–æ –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä—ã. –°—Ä–∞–≤–Ω–µ–Ω–∏—è ¬´–º–µ–Ω—å—à–µ-–±–æ–ª—å—à–µ¬ª –ø–æ –Ω–∏–º –Ω–µ –∏–º–µ—é—Ç —Å–º—ã—Å–ª–∞, –Ω–æ –∞–ª–≥–æ—Ä–∏—Ç–º—ã –º–æ–≥—É—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –∏—Ö –¥–ª—è —Ä–∞–∑–¥–µ–ª–µ–Ω–∏—è –¥–∞–Ω–Ω—ã—Ö –Ω–∞ –≥—Ä—É–ø–ø—ã. –¢–∞–∫–æ–π –ø–æ–¥—Ö–æ–¥ –æ—Å–æ–±–µ–Ω–Ω–æ —É–¥–æ–±–µ–Ω, –∫–æ–≥–¥–∞ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∫–∞—Ç–µ–≥–æ—Ä–∏–π –≤–µ–ª–∏–∫–æ, –∫–∞–∫ –≤ –Ω–∞—à–µ–º —Å–ª—É—á–∞–µ —Å–æ —Å—Ç—Ä–∞–Ω–∞–º–∏.

### 18

–ü–æ—Å—á–∏—Ç–∞—Ç—å, –¥–ª—è –∫–∞–∂–¥–æ–π —Å—Ç—Ä–∞–Ω—ã, –≤ –∫–∞–∫–∏–µ –≥–æ–¥—ã –Ω–∞–±–ª—é–¥–∞–µ—Ç—Å—è –Ω–∞–∏–±–æ–ª—å—à–∏–π —Ä–∞–∑—Ä—ã–≤ –º–µ–∂–¥—É –æ–∂–∏–¥–∞–µ–º–æ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –∏ –º—É–∂—á–∏–Ω. –í—ã–≤–µ—Å—Ç–∏ —Ç–æ–ø-5 —Å—Ç—Ä–∞–Ω —Å –Ω–∞–∏–±–æ–ª—å—à–µ–π —Å—Ä–µ–¥–Ω–µ–π —Ä–∞–∑–Ω–∏—Ü–µ–π –∑–∞ –≤–µ—Å—å –ø–µ—Ä–∏–æ–¥ –Ω–∞–±–ª—é–¥–µ–Ω–∏–π. –¢–∞–∫–∂–µ –≤—ã–≤–µ—Å—Ç–∏ —Ç–æ–ø-5 —Å—Ç—Ä–∞–Ω —Å –Ω–∞–∏–º–µ–Ω—å—à–µ–π —Ä–∞–∑–Ω–∏—Ü–µ–π.

–ò–Ω—Ç–µ—Ä–µ—Å–Ω–æ, –ø–æ—Ç–æ–º—É —á—Ç–æ:

–≠—Ç–æ –ø–æ–∑–≤–æ–ª—è–µ—Ç –≤—ã—è–≤–∏—Ç—å —Å—Ç—Ä–∞–Ω—ã, –≥–¥–µ –≥–µ–Ω–¥–µ—Ä–Ω—ã–π —Ä–∞–∑—Ä—ã–≤ –≤ –∑–¥–æ—Ä–æ–≤—å–µ –æ—Å–æ–±–µ–Ω–Ω–æ –∑–∞–º–µ—Ç–µ–Ω, –∏ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å, –∫–∞–∫ –æ–Ω –º–µ–Ω—è–ª—Å—è –≤–æ –≤—Ä–µ–º–µ–Ω–∏. –ú–æ–∂–µ—Ç –±—ã—Ç—å –ø–æ–ª–µ–∑–Ω–æ –¥–ª—è –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–π –≤ –æ–±–ª–∞—Å—Ç–∏ –∑–¥—Ä–∞–≤–æ–æ—Ö—Ä–∞–Ω–µ–Ω–∏—è –∏ —Å–æ—Ü–∏–∞–ª—å–Ω–æ–π –ø–æ–ª–∏—Ç–∏–∫–∏.

In [217]:
diff_df = merged_df.pivot_table(index=['CountryCode', 'YearCode'],
                                columns='SexCode',
                                values='Numeric').reset_index()
diff_df['female_male_diff'] = diff_df['FMLE'] - diff_df['MLE']
avg_diff = diff_df.groupby('CountryCode')['female_male_diff'].mean().sort_values(ascending=False)
top5_countries = avg_diff.head()
top5_countries

CountryCode
RUS    9.328148
BLR    8.973347
LTU    8.459569
EST    8.284474
SYC    8.003806
Name: female_male_diff, dtype: float64

In [218]:
top5_countries = avg_diff.tail()
top5_countries

CountryCode
NER    0.149450
KWT    0.063567
MDV    0.039512
QAT   -0.194712
MLI   -0.208137
Name: female_male_diff, dtype: float64

–ï—Å–ª–∏ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ —Ä–∞–∑–Ω–∏—Ü—É –≤ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –∂–µ–Ω—â–∏–Ω –∏ –º—É–∂—á–∏–Ω (female_male_diff), –≤–∏–¥–Ω–æ, —á—Ç–æ –≤ –Ω–µ–∫–æ—Ç–æ—Ä—ã—Ö —Å—Ç—Ä–∞–Ω–∞—Ö –æ–Ω–∞ –æ—á–µ–Ω—å –±–æ–ª—å—à–∞—è. –í –í–æ—Å—Ç–æ—á–Ω–æ–π –ï–≤—Ä–æ–ø–µ, –Ω–∞–ø—Ä–∏–º–µ—Ä, –†–æ—Å—Å–∏—è ‚Äî 9,3 –≥–æ–¥–∞, –ë–µ–ª–∞—Ä—É—Å—å ‚Äî 9,0, –õ–∏—Ç–≤–∞ ‚Äî 8,5, –≠—Å—Ç–æ–Ω–∏—è ‚Äî 8,3, –°–µ–π—à–µ–ª—å—Å–∫–∏–µ –æ—Å—Ç—Ä–æ–≤–∞ ‚Äî 8,0. –ê –≤–æ—Ç –≤ —Ä—è–¥–µ —Å—Ç—Ä–∞–Ω –ê—Ñ—Ä–∏–∫–∏ –∏ –ë–ª–∏–∂–Ω–µ–≥–æ –í–æ—Å—Ç–æ–∫–∞ —Ä–∞–∑–Ω–∏—Ü–∞ —Å–æ–≤—Å–µ–º –º–∞–ª–µ–Ω—å–∫–∞—è –∏–ª–∏ –¥–∞–∂–µ –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–∞—è: –ö–∞—Ç–∞—Ä ‚Äî -0,19, –ú–∞–ª–∏ ‚Äî -0,21, –ú–∞–ª—å–¥–∏–≤—ã ‚Äî 0,04.

–≠—Ç–æ –≥–æ–≤–æ—Ä–∏—Ç –æ —Ç–æ–º, —á—Ç–æ –≤ –í–æ—Å—Ç–æ—á–Ω–æ–π –ï–≤—Ä–æ–ø–µ –Ω—É–∂–Ω—ã —Å–ø–µ—Ü–∏–∞–ª—å–Ω—ã–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã –∏ –º–µ—Ä—ã, –∫–æ—Ç–æ—Ä—ã–µ –ø–æ–º–æ–≥—É—Ç —É–ª—É—á—à–∏—Ç—å –º—É–∂—Å–∫–æ–µ –∑–¥–æ—Ä–æ–≤—å–µ, –ø—Ä–µ–¥—É–ø—Ä–µ–¥–∏—Ç—å —Ö—Ä–æ–Ω–∏—á–µ—Å–∫–∏–µ –±–æ–ª–µ–∑–Ω–∏ –∏ —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å –∑–¥–æ—Ä–æ–≤—ã–π –æ–±—Ä–∞–∑ –∂–∏–∑–Ω–∏ —Å—Ä–µ–¥–∏ –º—É–∂—á–∏–Ω. –í —Å—Ç—Ä–∞–Ω–∞—Ö, –≥–¥–µ —Ä–∞–∑–Ω–∏—Ü–∞ –º–∏–Ω–∏–º–∞–ª—å–Ω–∞, –ø–æ–¥—Ö–æ–¥ –º–æ–∂–µ—Ç –±—ã—Ç—å –±–æ–ª–µ–µ —É–Ω–∏–≤–µ—Ä—Å–∞–ª—å–Ω—ã–º, –ø–æ—Ç–æ–º—É —á—Ç–æ –∑–¥–æ—Ä–æ–≤—å–µ –º—É–∂—á–∏–Ω –∏ –∂–µ–Ω—â–∏–Ω –ø—Ä–∏–º–µ—Ä–Ω–æ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–µ.

## –ë–æ–Ω—É—Å–Ω–∞—è —á–∞—Å—Ç—å –Ω–∞ –∞–Ω–∞–ª–∏–∑ —Ü–µ–ª–µ–≤–æ–π –ø–µ—Ä–µ–º–µ–Ω–Ω–æ–π (–¥–æ 5 –±–æ–Ω—É—Å–Ω—ã—Ö –±–∞–ª–ª–æ–≤)

–ü–æ—Å–ª–µ –≤—Å–µ–≥–æ –ø—Ä–æ–¥–µ–ª–∞–Ω–Ω–æ–≥–æ –∞–Ω–∞–ª–∏–∑–∞ –∏ –ø–æ–¥–≥–æ—Ç–æ–≤–∫–∏ –¥–∞–Ω–Ω—ã—Ö –º—ã –º–æ–∂–µ–º –ø–µ—Ä–µ–π—Ç–∏ –Ω–µ–ø–æ—Å—Ä–µ–¥—Å—Ç–≤–µ–Ω–Ω–æ –∫ –æ—Ç–≤–µ—Ç—É –Ω–∞ –∏—Å—Ö–æ–¥–Ω—ã–π –≤–æ–ø—Ä–æ—Å –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è, –∫–æ—Ç–æ—Ä—ã–π –±—ã–ª —Å—Ñ–æ—Ä–º—É–ª–∏—Ä–æ–≤–∞–Ω –≤–∞–º–∏ –≤ –∑–∞–¥–∞–Ω–∏–∏ 3.

### 19

***–ë–æ–Ω—É—Å (5 –±–æ–Ω. –±–∞–ª–ª–æ–≤):*** –î–∞–π—Ç–µ —Ä–∞–∑–≤–µ—Ä–Ω—É—Ç—ã–π, –æ–±–æ—Å–Ω–æ–≤–∞–Ω–Ω—ã–π, –ø–æ–¥–∫—Ä–µ–ø–ª–µ–Ω–Ω—ã–π –¥–∞–Ω–Ω—ã–º–∏ –∏ –Ω–∞–ø–∏—Å–∞–Ω–Ω—ã–º –≤–∞–º–∏ –∫–æ–¥–æ–º –æ—Ç–≤–µ—Ç –Ω–∞ –≤–æ–ø—Ä–æ—Å, –≤–ª–∏—è—é—Ç –ª–∏ –ø—Ä–∏–∑–Ω–∞–∫–∏ –∑–∞–≤–∏—Å–∏–º–æ–π —Ç–∞–±–ª–∏—Ü—ã –Ω–∞ —Ü–µ–ª–µ–≤—É—é –ø–µ—Ä–µ–º–µ–Ω–Ω—É—é –∏–∑ –≥–ª–∞–≤–Ω–æ–π —Ç–∞–±–ª–∏—Ü—ã –∏, –µ—Å–ª–∏ –¥–∞, —Ç–æ –∫–∞–∫–∏–º –∏–º–µ–Ω–Ω–æ –æ–±—Ä–∞–∑–æ–º –≤–ª–∏—è—é—Ç?

–û–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –∞—Ä–≥—É–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ –ø–æ–ª—É—á–µ–Ω–Ω—ã–µ –≤–∞–º–∏ —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã –∏ –≤—ã–≤–æ–¥—ã. –ß–µ–º –ø–æ–¥—Ä–æ–±–Ω–µ–µ –∏ –æ–±–æ—Å–Ω–æ–≤–∞–Ω–Ω–µ–µ –∞–Ω–∞–ª–∏–∑ –≤—ã –ø—Ä–æ–≤–µ–¥–µ—Ç–µ –≤ —Ä–∞–º–∫–∞—Ö –¥–∞–Ω–Ω–æ–≥–æ –±–æ–Ω—É—Å–Ω–æ–≥–æ –∑–∞–¥–∞–Ω–∏—è, —Ç–µ–º –±–æ–ª—å—à–µ –±–æ–Ω—É—Å–Ω—ã—Ö –±–∞–ª–ª–æ–≤ –ø–æ–ª—É—á–∏—Ç–µ! –í—ã –º–æ–∂–µ—Ç–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –ø–æ–¥—Ö–æ–¥—ã –∏ –º–µ—Ç–æ–¥—ã –∏–∑ —Ä–∞—Å—Å–º–æ—Ç—Ä–µ–Ω–Ω—ã—Ö –Ω–∞ —Å–µ–º–∏–Ω–∞—Ä–µ –∏ –≤ —Ä–∞–º–∫–∞—Ö –¥–∞–Ω–Ω–æ–≥–æ –¥–æ–º–∞—à–Ω–µ–≥–æ –∑–∞–¥–∞–Ω–∏—è, –∞ –º–æ–∂–µ—Ç–µ –ø—Ä–∏–¥—É–º–∞—Ç—å –∏ —á—Ç–æ-—Ç–æ —Å–≤–æ—ë. –ö—Ä–µ–∞—Ç–∏–≤–Ω–æ—Å—Ç—å –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ –ø—Ä–∏–≤–µ—Ç—Å—Ç–≤—É–µ—Ç—Å—è!

–ù–∞—à–∞ —Ü–µ–ª—å: –ø—Ä–æ–≤–µ—Ä–∏—Ç—å, –≤–ª–∏—è–µ—Ç –ª–∏ —É—Ä–æ–≤–µ–Ω—å –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –∏ –¥—Ä—É–≥–∏–µ –≤–Ω–µ—à–Ω–∏–µ –ø—Ä–∏–∑–Ω–∞–∫–∏ –Ω–∞ –æ–∂–∏–¥–∞–µ–º—É—é –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏. –ú—ã –±—É–¥–µ–º —Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ –∫–æ—Ä—Ä–µ–ª—è—Ü–∏–∏ –∏ —É—Å—Ä–µ–¥–Ω—ë–Ω–Ω—ã–µ –ø–æ–∫–∞–∑–∞—Ç–µ–ª–∏, —á—Ç–æ–±—ã –ø–æ–Ω—è—Ç—å –Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –≤–ª–∏—è–Ω–∏—è.

In [219]:
# –°–Ω–∞—á–∞–ª–∞ —Å–æ–∑–¥–∞—ë–º –Ω–æ–≤—ã–π —Å—Ç–æ–ª–±–µ—Ü, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–∫–∞–∑—ã–≤–∞–µ—Ç —Å—Ä–µ–¥–Ω–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –∞–ª–∫–æ–≥–æ–ª—è –Ω–∞ —á–µ–ª–æ–≤–µ–∫–∞ –ø–æ –≤—Å–µ–º –≤–∏–¥–∞–º
alcohol_cols = ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']
merged_df['total_servings'] = merged_df[alcohol_cols].mean(axis=1)
# –°—á–∏—Ç–∞–µ–º –∫–æ—Ä—Ä–µ–ª—è—Ü–∏–∏ –º–µ–∂–¥—É –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏ (Numeric) –∏ –≤—Å–µ–º–∏ –≤–∏–¥–∞–º–∏ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è
corrs = merged_df[['Numeric'] + alcohol_cols].corr()['Numeric'].sort_values(ascending=False)
corrs

Numeric                         1.000000
wine_servings                   0.129527
beer_servings                   0.124204
total_litres_of_pure_alcohol    0.112060
spirit_servings                 0.099499
Name: Numeric, dtype: float64

–ö–æ—Ä—Ä–µ–ª—è—Ü–∏–∏ –ø–æ–ª—É—á–∏–ª–∏—Å—å –æ–∫–æ–ª–æ 0.1‚Äì0.13 ‚Äî —ç—Ç–æ –æ—á–µ–Ω—å —Å–ª–∞–±–∞—è —Å–≤—è–∑—å, –ø—Ä–∞–∫—Ç–∏—á–µ—Å–∫–∏ –Ω–µ–∑–Ω–∞—á–∏–º–∞—è.

–ü–æ–ª–æ–∂–∏—Ç–µ–ª—å–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≥–æ–≤–æ—Ä—è—Ç –æ —Ç–æ–º, —á—Ç–æ —Å —Ä–æ—Å—Ç–æ–º –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è Numeric —Å–ª–µ–≥–∫–∞ —É–≤–µ–ª–∏—á–∏–≤–∞–µ—Ç—Å—è, –Ω–æ —ç—Ñ—Ñ–µ–∫—Ç –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–π.

–í–ª–∏—è–Ω–∏–µ —Å–ø–∏—Ä—Ç–Ω–æ–≥–æ –∏ –ø–∏–≤–∞ —á—É—Ç—å –Ω–∏–∂–µ, —á–µ–º –≤–ª–∏—è–Ω–∏–µ –≤–∏–Ω–∞.

–í —Ü–µ–ª–æ–º, —ç—Ç–æ –ø–æ–∫–∞–∑—ã–≤–∞–µ—Ç, —á—Ç–æ –∞–ª–∫–æ–≥–æ–ª—å –Ω–µ —è–≤–ª—è–µ—Ç—Å—è –∫–ª—é—á–µ–≤—ã–º —Ñ–∞–∫—Ç–æ—Ä–æ–º, –æ–ø—Ä–µ–¥–µ–ª—è—é—â–∏–º –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –≤ –Ω–∞—à–µ–º –Ω–∞–±–æ—Ä–µ –¥–∞–Ω–Ω—ã—Ö. –í–µ—Ä–æ—è—Ç–Ω–æ, –Ω–∞ –Ω–µ—ë —Å–∏–ª—å–Ω–µ–µ –≤–ª–∏—è—é—Ç –¥—Ä—É–≥–∏–µ –≤–µ—â–∏ ‚Äî –¥–æ—Ö–æ–¥—ã, –∫–∞—á–µ—Å—Ç–≤–æ –∑–¥—Ä–∞–≤–æ–æ—Ö—Ä–∞–Ω–µ–Ω–∏—è, –æ–±—Ä–∞–∑ –∂–∏–∑–Ω–∏, —ç–∫–æ–ª–æ–≥–∏—è –∏ —Ç–∞–∫ –¥–∞–ª–µ–µ.

–¢–æ –µ—Å—Ç—å —ç—Ç–∏ –¥–∞–Ω–Ω—ã–µ –Ω–µ –æ–ø—Ä–æ–≤–µ—Ä–≥–∞—é—Ç –ø–æ—Ç–µ–Ω—Ü–∏–∞–ª—å–Ω–æ–µ –Ω–µ–≥–∞—Ç–∏–≤–Ω–æ–µ –≤–ª–∏—è–Ω–∏–µ –∞–ª–∫–æ–≥–æ–ª—è –Ω–∞ –∑–¥–æ—Ä–æ–≤—å–µ, –Ω–æ –Ω–∞ —É—Ä–æ–≤–Ω–µ –∞–≥—Ä–µ–≥–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö –ø–æ–∫–∞–∑–∞—Ç–µ–ª–µ–π –ø–æ —Å—Ç—Ä–∞–Ω–∞–º –∏ –≥–æ–¥–∞–º —ç—Ñ—Ñ–µ–∫—Ç –ø–æ—á—Ç–∏ ¬´—Ä–∞–∑–º–∞–∑–∞–Ω¬ª –∏ –æ—á–µ–Ω—å —Å–ª–∞–±—ã–π.

In [220]:
# –°—á–∏—Ç–∞–µ–º —Å—Ä–µ–¥–Ω—é—é –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –∂–∏–∑–Ω–∏ –∏ —Å—Ä–µ–¥–Ω–µ–µ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏–µ –∞–ª–∫–æ–≥–æ–ª—è –ø–æ —Å—Ç—Ä–∞–Ω–∞–º –∏ –ø–æ–ª—É
grouped = merged_df.groupby(['CountryCode','SexCode']).agg({
    'Numeric':'mean',
    'total_litres_of_pure_alcohol':'mean'
}).reset_index()

# –û–ø—Ä–µ–¥–µ–ª—è–µ–º —Ä–∞–∑–Ω–∏—Ü—É –≤ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º–µ–∂–¥—É –∂–µ–Ω—â–∏–Ω–∞–º–∏ –∏ –º—É–∂—á–∏–Ω–∞–º–∏ –≤ –∫–∞–∂–¥–æ–π —Å—Ç—Ä–∞–Ω–µ
grouped['female_male_diff'] = grouped.groupby('CountryCode')['Numeric'].transform(lambda x: x.max() - x.min())

# –°–º–æ—Ç—Ä–∏–º 10 —Å—Ç—Ä–∞–Ω —Å —Å–∞–º–æ–π –±–æ–ª—å—à–æ–π —Ä–∞–∑–Ω–∏—Ü–µ–π
grouped.sort_values('female_male_diff', ascending=False).head(10)

,CountryCode,SexCode,Numeric,total_litres_of_pure_alcohol,female_male_diff
442,RUS,FMLE,51.803535,11.5,9.448889
441,RUS,BTSX,47.214438,11.5,9.448889
443,RUS,MLE,42.354646,11.5,9.448889
60,BLR,BTSX,49.315830,14.4,9.107287
61,BLR,FMLE,53.746556,14.4,9.107287
62,BLR,MLE,44.639269,14.4,9.107287
311,LTU,MLE,46.814081,12.9,8.546803
310,LTU,FMLE,55.360884,12.9,8.546803
309,LTU,BTSX,51.319116,12.9,8.546803
165,EST,BTSX,51.849642,9.5,8.310335

docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html

–ï—Å–ª–∏ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å –Ω–∞ –∫–æ–Ω–∫—Ä–µ—Ç–Ω—ã–µ —Å—Ç—Ä–∞–Ω—ã –í–æ—Å—Ç–æ—á–Ω–æ–π –ï–≤—Ä–æ–ø—ã ‚Äî –†–æ—Å—Å–∏—è, –ë–µ–ª–∞—Ä—É—Å—å, –õ–∏—Ç–≤–∞, –≠—Å—Ç–æ–Ω–∏—è ‚Äî –≤–∏–¥–Ω–æ, —á—Ç–æ –∂–µ–Ω—â–∏–Ω—ã –∂–∏–≤—É—Ç –∑–∞–º–µ—Ç–Ω–æ –¥–æ–ª—å—à–µ –º—É–∂—á–∏–Ω: —Ä–∞–∑–Ω–∏—Ü–∞ —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –æ—Ç 8,3 –¥–æ 9,4 –ª–µ—Ç. –ù–∞–ø—Ä–∏–º–µ—Ä, –≤ –†–æ—Å—Å–∏–∏ –∂–µ–Ω—â–∏–Ω—ã –≤ —Å—Ä–µ–¥–Ω–µ–º 51,8 –≥–æ–¥–∞, –º—É–∂—á–∏–Ω—ã ‚Äî 42,3‚Äì47,2; –≤ –ë–µ–ª–∞—Ä—É—Å–∏ –∂–µ–Ω—â–∏–Ω—ã ‚Äî 53,7, –º—É–∂—á–∏–Ω—ã ‚Äî 44,6‚Äì49,3.

–£—Ä–æ–≤–µ–Ω—å –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –≤–∞—Ä—å–∏—Ä—É–µ—Ç—Å—è, –Ω–æ –Ω–µ –∫–æ—Ä—Ä–µ–ª–∏—Ä—É–µ—Ç –Ω–∞–ø—Ä—è–º—É—é —Å —Ä–∞–∑–Ω–∏—Ü–µ–π –º–µ–∂–¥—É –ø–æ–ª–∞–º–∏: –≤ –†–æ—Å—Å–∏–∏ 11,5 –ª–∏—Ç—Ä–∞ –Ω–∞ —á–µ–ª–æ–≤–µ–∫–∞, –≤ –ë–µ–ª–∞—Ä—É—Å–∏ 14,4, –õ–∏—Ç–≤–∞ ‚Äî 12,9, –≠—Å—Ç–æ–Ω–∏—è ‚Äî 9,5. –ú—É–∂—á–∏–Ω—ã —Å –±–æ–ª–µ–µ –Ω–∏–∑–∫–æ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏ –Ω–µ –∏–º–µ—é—Ç —è–≤–Ω–æ –±–æ–ª—å—à–µ–≥–æ –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è, —á–µ–º –∂–µ–Ω—â–∏–Ω—ã.

–≠—Ç–æ —É–∫–∞–∑—ã–≤–∞–µ—Ç –Ω–∞ —Ç–æ, —á—Ç–æ —Ñ–∞–∫—Ç–æ—Ä—ã, –≤–ª–∏—è—é—â–∏–µ –Ω–∞ —Ä–∞–∑–Ω–∏—Ü—É –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –∂–∏–∑–Ω–∏ –º–µ–∂–¥—É –ø–æ–ª–∞–º–∏, —Å–∫–æ—Ä–µ–µ —Å–æ—Ü–∏–∞–ª—å–Ω–æ-—ç–∫–æ–Ω–æ–º–∏—á–µ—Å–∫–∏–µ, –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏–µ –∏ –ø–æ–≤–µ–¥–µ–Ω—á–µ—Å–∫–∏–µ, –∞ –Ω–µ –ø—Ä–æ—Å—Ç–æ –∞–ª–∫–æ–≥–æ–ª—å.

–í—ã–≤–æ–¥: –∑–Ω–∞—á–∏—Ç–µ–ª—å–Ω—ã–π —Ä–∞–∑—Ä—ã–≤ –º–µ–∂–¥—É –º—É–∂—á–∏–Ω–∞–º–∏ –∏ –∂–µ–Ω—â–∏–Ω–∞–º–∏ –≤ —ç—Ç–∏—Ö —Å—Ç—Ä–∞–Ω–∞—Ö –≥–æ–≤–æ—Ä–∏—Ç –æ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ—Å—Ç–∏ –≤–Ω–µ–¥—Ä–µ–Ω–∏—è –ø—Ä–æ–≥—Ä–∞–º–º –∏ –∏–Ω–∏—Ü–∏–∞—Ç–∏–≤, –Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–Ω—ã—Ö –Ω–∞ –∑–¥–æ—Ä–æ–≤—å–µ –º—É–∂—á–∏–Ω –∏ –ø—Ä–æ—Ñ–∏–ª–∞–∫—Ç–∏–∫—É —Ö—Ä–æ–Ω–∏—á–µ—Å–∫–∏—Ö –∑–∞–±–æ–ª–µ–≤–∞–Ω–∏–π. –ê–ª–∫–æ–≥–æ–ª—å –ø—Ä–∏ —ç—Ç–æ–º –Ω–µ –≤—ã—Å—Ç—É–ø–∞–µ—Ç –≥–ª–∞–≤–Ω—ã–º –æ–±—ä—è—Å–Ω—è—é—â–∏–º

---

## üìà –ò—Ç–æ–≥ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏—è

–í —Ö–æ–¥–µ —Ä–∞–±–æ—Ç—ã –±—ã–ª–∏ –ø—Ä–æ–∞–Ω–∞–ª–∏–∑–∏—Ä–æ–≤–∞–Ω—ã –¥–∞–Ω–Ω—ã–µ –ø–æ 193 —Å—Ç—Ä–∞–Ω–∞–º.  
–û–±–Ω–∞—Ä—É–∂–µ–Ω–∞ —Å–ª–∞–±–∞—è –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω–∞—è –∫–æ—Ä—Ä–µ–ª—è—Ü–∏—è –º–µ–∂–¥—É —É—Ä–æ–≤–Ω–µ–º –ø–æ—Ç—Ä–µ–±–ª–µ–Ω–∏—è –∞–ª–∫–æ–≥–æ–ª—è –∏ —Å—Ä–µ–¥–Ω–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é –∂–∏–∑–Ω–∏, –æ–¥–Ω–∞–∫–æ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç—å –Ω–µ —è–≤–ª—è–µ—Ç—Å—è –ª–∏–Ω–µ–π–Ω–æ–π –∏ –º–æ–∂–µ—Ç –∑–∞–≤–∏—Å–µ—Ç—å –æ—Ç –º–Ω–æ–∂–µ—Å—Ç–≤–∞ —Å–æ—Ü–∏–∞–ª—å–Ω—ã—Ö –∏ —ç–∫–æ–Ω–æ–º–∏—á–µ—Å–∫–∏—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤.

–ü—Ä–æ–µ–∫—Ç –¥–µ–º–æ–Ω—Å—Ç—Ä–∏—Ä—É–µ—Ç –±–∞–∑–æ–≤—ã–µ –Ω–∞–≤—ã–∫–∏ –∞–Ω–∞–ª–∏–∑–∞ –¥–∞–Ω–Ω—ã—Ö: –∑–∞–≥—Ä—É–∑–∫—É, –æ—á–∏—Å—Ç–∫—É, –æ–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ —Ç–∞–±–ª–∏—Ü –∏ –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—é.

---

## üöÄ –ö–∞–∫ –∑–∞–ø—É—Å—Ç–∏—Ç—å
–í—ã –º–æ–∂–µ—Ç–µ –æ—Ç–∫—Ä—ã—Ç—å —ç—Ç–æ—Ç –Ω–æ—É—Ç–±—É–∫ –≤ Google Colab:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/your_username/alcohol-life-expectancy-analysis/blob/main/notebooks/analysis.ipynb)